/**
 * Sources of the product-page photographs, keyed by their public path. Each
 * is a real photograph from Wikimedia Commons, downloaded once (1920 px max,
 * WebP) and served from this site: Commons rate-limits server-side image
 * fetches, so hotlinking is not reliable.
 *
 * CC BY and CC BY-SA files require a credit (author, source, licence) where
 * they are shown; CC0 and public-domain files need none. The credit line
 * (components/photo-credits.tsx) is currently not rendered.
 */

/** Where a licensed third-party photograph came from, and the terms it is used under. */
export type PhotoCredit = {
  author: string;
  license: string;
  licenseUrl?: string;
  /** The file's description page (licence, author and history). */
  source: string;
  /** The direct image URL the local copy was downloaded from. */
  original: string;
  /** Any edit beyond resizing and WebP conversion. */
  changes?: string;
};

export const productPhotoCredits: Record<string, PhotoCredit> = {
  "/images/products/agri/mango/mango-hero.webp": {
    author: "Hajia Hijjah",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Ripe_fresh_mangoes.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Ripe_fresh_mangoes.jpg/1920px-Ripe_fresh_mangoes.jpg",
  },
  "/images/products/agri/mango/mango-use-fresh.webp": {
    author: "SarKaLay စာကလေး",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Ripe_mango_(23173).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Ripe_mango_%2823173%29.jpg/1920px-Ripe_mango_%2823173%29.jpg",
  },
  "/images/products/agri/mango/mango-use-drinks.webp": {
    author: "CYAN",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mango_juice_a0.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Mango_juice_a0.jpg/1920px-Mango_juice_a0.jpg",
  },
  "/images/products/agri/mango/mango-use-processing.webp": {
    author: "Gaurav Dhwaj Khadka",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Mango_pulp.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Mango_pulp.jpg/1920px-Mango_pulp.jpg",
  },
  "/images/products/agri/mango/mango-use-desserts.webp": {
    author: "Subhransuphotography",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mango_Custard-Puri_Odisha-IMG_1041.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Mango_Custard-Puri_Odisha-IMG_1041.jpg/1920px-Mango_Custard-Puri_Odisha-IMG_1041.jpg",
  },
  "/images/products/agri/banana/banana-hero.webp": {
    author: "Wilfredor",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Cavendish_banana_from_Maracaibo.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Cavendish_banana_from_Maracaibo.jpg/1920px-Cavendish_banana_from_Maracaibo.jpg",
  },
  "/images/products/agri/banana/banana-detail.webp": {
    author: "Noblevmy at Malayalam Wikipedia",
    license: "CC BY 2.5",
    licenseUrl: "https://creativecommons.org/licenses/by/2.5",
    source: "https://commons.wikimedia.org/wiki/File:Kadalikkula.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Kadalikkula.JPG/1920px-Kadalikkula.JPG",
  },
  "/images/products/agri/grapes/grapes-hero.webp": {
    author: "Anna.Massini",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Grappolo_di_uva_nera.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Grappolo_di_uva_nera.jpg/1920px-Grappolo_di_uva_nera.jpg",
  },
  "/images/products/agri/grapes/grapes-detail.webp": {
    author: "Krzysztof Golik",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Vine_in_the_vineyard_in_Kaysersberg.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Vine_in_the_vineyard_in_Kaysersberg.jpg/1920px-Vine_in_the_vineyard_in_Kaysersberg.jpg",
  },
  "/images/products/agri/grapes/grapes-green.webp": {
    author: "Fumikas Sagisavas",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Green_grapes_(20240716).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Green_grapes_%2820240716%29.jpg/1920px-Green_grapes_%2820240716%29.jpg",
  },
  "/images/products/agri/pomegranate/pomegranate-hero.webp": {
    author: "Rhododendrites",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Pomegranate_on_white.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Pomegranate_on_white.jpg/1920px-Pomegranate_on_white.jpg",
  },
  "/images/products/agri/pomegranate/pomegranate-detail.webp": {
    author: "Ivar Leidus",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Pomegranate_(opened).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Pomegranate_%28opened%29.jpg/1920px-Pomegranate_%28opened%29.jpg",
  },
  "/images/products/agri/pomegranate/pomegranate-use-fresh.webp": {
    author: "Ivar Leidus",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Pomegranate_fruit_-_whole_and_piece_with_arils.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Pomegranate_fruit_-_whole_and_piece_with_arils.jpg/1920px-Pomegranate_fruit_-_whole_and_piece_with_arils.jpg",
  },
  "/images/products/agri/pomegranate/pomegranate-use-salad.webp": {
    author: "dnm",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Fruktsallad_(Fruit_salad).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/7/74/Fruktsallad_%28Fruit_salad%29.jpg",
  },
  "/images/products/agri/pomegranate/pomegranate-use-juice.webp": {
    author: "Augustus Binu",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Pomegranate_juice_with_slice.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Pomegranate_juice_with_slice.jpg/1920px-Pomegranate_juice_with_slice.jpg",
  },
  "/images/products/agri/pomegranate/pomegranate-use-processing.webp": {
    author: "HaJunkiyada",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Liat_Portal_for_Foodie_Disorder_-_Pomegranate_Seeds.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Liat_Portal_for_Foodie_Disorder_-_Pomegranate_Seeds.jpg/1920px-Liat_Portal_for_Foodie_Disorder_-_Pomegranate_Seeds.jpg",
  },
  "/images/products/agri/orange/orange-hero.webp": {
    author: "USDA Agricultural Research Service",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Ambersweet_oranges.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Ambersweet_oranges.jpg/1920px-Ambersweet_oranges.jpg",
  },
  "/images/products/agri/orange/orange-detail.webp": {
    author: "Scott Bauer, USDA Agricultural Research Service",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Oranges_and_orange_juice.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/5/5a/Oranges_and_orange_juice.jpg",
  },
  "/images/products/agri/orange/orange-slice.webp": {
    author: "Evan-Amos",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Orange-Fruit-Pieces.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Orange-Fruit-Pieces.jpg/1920px-Orange-Fruit-Pieces.jpg",
  },
  "/images/products/agri/orange/orange-tree.webp": {
    author: "Zeynel Cebeci",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Local_Orange_Variety_of_Kozan_-_Kozan_Yerli_Portakal_04.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Local_Orange_Variety_of_Kozan_-_Kozan_Yerli_Portakal_04.jpg/1920px-Local_Orange_Variety_of_Kozan_-_Kozan_Yerli_Portakal_04.jpg",
  },
  "/images/products/agri/chikoo/chikoo-hero.webp": {
    author: "KIRUTHIKA OFF",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Sapodilla_fruit_image.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Sapodilla_fruit_image.jpg/1920px-Sapodilla_fruit_image.jpg",
  },
  "/images/products/agri/chikoo/chikoo-detail.webp": {
    author: "Kristof Zyskowski & Yulia Bereshpolova",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Sapotaceae-_Manilkara_zapota_(sapodilla).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Sapotaceae-_Manilkara_zapota_%28sapodilla%29.jpg/1920px-Sapotaceae-_Manilkara_zapota_%28sapodilla%29.jpg",
  },
  "/images/products/agri/papaya/papaya-hero.webp": {
    author: "Ivar Leidus",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Papaya_-_longitudinal_section.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Papaya_-_longitudinal_section.jpg/1920px-Papaya_-_longitudinal_section.jpg",
  },
  "/images/products/agri/papaya/papaya-detail.webp": {
    author: "Gerda Arendt",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Papaya_fruits_on_tree,_San_Andres.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Papaya_fruits_on_tree%2C_San_Andres.jpg/1920px-Papaya_fruits_on_tree%2C_San_Andres.jpg",
  },
  "/images/products/agri/papaya/papaya-use-fresh.webp": {
    author: "Billjones94",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Longitudinal_section_of_ripe_papaya_fruit_in_West_Bengal,_India.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Longitudinal_section_of_ripe_papaya_fruit_in_West_Bengal%2C_India.jpg/1920px-Longitudinal_section_of_ripe_papaya_fruit_in_West_Bengal%2C_India.jpg",
  },
  "/images/products/agri/papaya/papaya-use-drinks.webp": {
    author: "El Mono Español",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Batido_de_papaya.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Batido_de_papaya.jpg/1920px-Batido_de_papaya.jpg",
  },
  "/images/products/agri/papaya/papaya-use-salad.webp": {
    author: "Vee Satayamas",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Blue_crab_papaya_salad,_Ban-kru-eed,_Rayong.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Blue_crab_papaya_salad%2C_Ban-kru-eed%2C_Rayong.jpg/1920px-Blue_crab_papaya_salad%2C_Ban-kru-eed%2C_Rayong.jpg",
  },
  "/images/products/agri/papaya/papaya-use-processing.webp": {
    author: "Evening42",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Papaya_cubes.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Papaya_cubes.jpg/1920px-Papaya_cubes.jpg",
  },
  "/images/products/agri/guava/guava-hero.webp": {
    author: "Thamizhpparithi Maari",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Guava_-_Psidium_guajava_fruit_of_Tamilnadu.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Guava_-_Psidium_guajava_fruit_of_Tamilnadu.jpg/1920px-Guava_-_Psidium_guajava_fruit_of_Tamilnadu.jpg",
  },
  "/images/products/agri/guava/guava-detail.webp": {
    author: "NanaYawBotar",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Unripe_guava_fruit.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/e/ee/Unripe_guava_fruit.jpg",
  },
  "/images/products/agri/guava/guava-slice.webp": {
    author: "Hungda",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:%E1%BB%94i_%C4%91%C3%A0o_-pink_guava.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/4/40/%E1%BB%94i_%C4%91%C3%A0o_-pink_guava.jpg",
  },
  "/images/products/agri/guava/guava-white.webp": {
    author: "GTSPACE",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:GUAVA_FRUIT.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/GUAVA_FRUIT.jpg/1920px-GUAVA_FRUIT.jpg",
  },
  "/images/products/agri/beans/beans-blanched.webp": {
    author: "Alabama Extension",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Green_Beans_(Alabama_Extension).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Green_Beans_%28Alabama_Extension%29.jpg/1920px-Green_Beans_%28Alabama_Extension%29.jpg",
  },
  "/images/products/agri/beans/beans-bowl.webp": {
    author: "www.Pixel.la Free Stock Photos",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Green_beans_in_a_wooden_box.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Green_beans_in_a_wooden_box.jpg/1920px-Green_beans_in_a_wooden_box.jpg",
  },
  "/images/products/agri/beans/beans-detail.webp": {
    author: "Jeffery Martin",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Green_beans_in_a_pile.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Green_beans_in_a_pile.JPG/1920px-Green_beans_in_a_pile.JPG",
  },
  "/images/products/agri/beans/beans-hero.webp": {
    author: "Gaurav Dhwaj Khadka",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Green_Beans_1.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Green_Beans_1.jpg/1920px-Green_Beans_1.jpg",
  },
  "/images/products/agri/bitter-gourd/bitter-gourd-detail.webp": {
    author: "စာကလေး SarKaLay",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:%E1%80%80%E1%80%BC%E1%80%80%E1%80%BA%E1%80%9F%E1%80%84%E1%80%BA%E1%80%B8%E1%80%81%E1%80%AB%E1%80%B8%E1%80%9E%E1%80%AE%E1%80%B8_Bitter_Melon.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/%E1%80%80%E1%80%BC%E1%80%80%E1%80%BA%E1%80%9F%E1%80%84%E1%80%BA%E1%80%B8%E1%80%81%E1%80%AB%E1%80%B8%E1%80%9E%E1%80%AE%E1%80%B8_Bitter_Melon.jpg/1920px-%E1%80%80%E1%80%BC%E1%80%80%E1%80%BA%E1%80%9F%E1%80%84%E1%80%BA%E1%80%B8%E1%80%81%E1%80%AB%E1%80%B8%E1%80%9E%E1%80%AE%E1%80%B8_Bitter_Melon.jpg",
  },
  "/images/products/agri/bitter-gourd/bitter-gourd-hero.webp": {
    author: "Bhaskaranaidu",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Bitter_gourd_at_Hyderabad_market.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Bitter_gourd_at_Hyderabad_market.jpg/1920px-Bitter_gourd_at_Hyderabad_market.jpg",
  },
  "/images/products/agri/drumstick/drumstick-hero.webp": {
    author: "David E Mead",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Ben-oil_tree_pods_(marketed)_2.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Ben-oil_tree_pods_%28marketed%29_2.jpg/1920px-Ben-oil_tree_pods_%28marketed%29_2.jpg",
  },
  "/images/products/agri/drumstick/drumstick-use-curry.webp": {
    author: "Anamika mathur",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Laajawaab_Drumstick_Curry.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Laajawaab_Drumstick_Curry.jpg/1280px-Laajawaab_Drumstick_Curry.jpg",
  },
  "/images/products/agri/drumstick/drumstick-use-frozen.webp": {
    author: "Judgefloro",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:2301Moringa_oleifera_pod_(seedpod)_textures_37.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/2301Moringa_oleifera_pod_%28seedpod%29_textures_37.jpg/1920px-2301Moringa_oleifera_pod_%28seedpod%29_textures_37.jpg",
  },
  "/images/products/agri/drumstick/drumstick-use-sambar.webp": {
    author: "Booradleyp1",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Sambar_(drumstick).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Sambar_%28drumstick%29.jpg/1920px-Sambar_%28drumstick%29.jpg",
  },
  "/images/products/agri/drumstick/drumstick-use-soup.webp": {
    author: "Wagaung",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    source: "https://commons.wikimedia.org/wiki/File:Dunt-dalun_chin-yei_1760.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/4/41/Dunt-dalun_chin-yei_1760.JPG",
  },
  "/images/products/agri/eggplant/eggplant-detail.webp": {
    author: "Karen and Brad Emerson",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Eggplant_(27751779984).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Eggplant_%2827751779984%29.jpg/1920px-Eggplant_%2827751779984%29.jpg",
  },
  "/images/products/agri/eggplant/eggplant-hero.webp": {
    author: "Fumikas Sagisavas",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Round_eggplant_(2).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Round_eggplant_%282%29.jpg/1920px-Round_eggplant_%282%29.jpg",
  },
  "/images/products/agri/frozen-peas/frozen-peas-detail.webp": {
    author: "Paul Wilkinson",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Frozen_Peas_(8042519481).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Frozen_Peas_%288042519481%29.jpg/1920px-Frozen_Peas_%288042519481%29.jpg",
  },
  "/images/products/agri/frozen-peas/frozen-peas-hero.webp": {
    author: "Jina Lee",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    source: "https://commons.wikimedia.org/wiki/File:Frozen_peas.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Frozen_peas.JPG/1920px-Frozen_peas.JPG",
  },
  "/images/products/agri/frozen-peas/frozen-peas-pods.webp": {
    author: "Fumikas Sagisavas",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Green_pea_pods.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Green_pea_pods.jpg/1920px-Green_pea_pods.jpg",
  },
  "/images/products/agri/frozen-peas/frozen-peas-scoop.webp": {
    author: "Ruth Hartnup",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Peas_(484346231).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Peas_%28484346231%29.jpg/1920px-Peas_%28484346231%29.jpg",
  },
  "/images/products/agri/okra/okra-hero.webp": {
    author: "စာကလေး",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Okra_Ron-Pa-Ti-Tee.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Okra_Ron-Pa-Ti-Tee.jpg/1920px-Okra_Ron-Pa-Ti-Tee.jpg",
  },
  "/images/products/agri/okra/okra-use-curry.webp": {
    author: "やましこ",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Bhindi_masala_(49657981033).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Bhindi_masala_%2849657981033%29.jpg/1920px-Bhindi_masala_%2849657981033%29.jpg",
  },
  "/images/products/agri/okra/okra-use-fried.webp": {
    author: "Ashwani Singh",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Karari_bhindi_!!!.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Karari_bhindi_%21%21%21.jpg/1920px-Karari_bhindi_%21%21%21.jpg",
  },
  "/images/products/agri/okra/okra-use-frozen.webp": {
    author: "Alabama Extension",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Frozen_Okra.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Frozen_Okra.jpg/1920px-Frozen_Okra.jpg",
  },
  "/images/products/agri/okra/okra-use-stew.webp": {
    author: "Benoît Prieur",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Du_bamia_avec_du_riz_en_f%C3%A9vrier_2022.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Du_bamia_avec_du_riz_en_f%C3%A9vrier_2022.jpg/1920px-Du_bamia_avec_du_riz_en_f%C3%A9vrier_2022.jpg",
  },
  "/images/products/spices/black-pepper-hero.webp": {
    author: "Misterneedlemouse",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Tellicherry_Black_Peppercorns.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Tellicherry_Black_Peppercorns.jpg/1920px-Tellicherry_Black_Peppercorns.jpg",
  },
  "/images/products/spices/black-pepper-vine.webp": {
    author: "Ronambiar",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Piper_nigrum_2.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Piper_nigrum_2.jpg/1920px-Piper_nigrum_2.jpg",
  },
  "/images/products/spices/black-pepper-culinary-use.webp": {
    author: "Daderot",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Steak_and_asparagus_on_peas,_with_olive_oil_and_black_pepper_-_Massachusetts.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Steak_and_asparagus_on_peas%2C_with_olive_oil_and_black_pepper_-_Massachusetts.jpg/1920px-Steak_and_asparagus_on_peas%2C_with_olive_oil_and_black_pepper_-_Massachusetts.jpg",
  },
  "/images/products/spices/cinnamon-hero.webp": {
    author: "Fumikas Sagisavas",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Cinnamon_sticks_(3).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Cinnamon_sticks_%283%29.jpg/1920px-Cinnamon_sticks_%283%29.jpg",
  },
  "/images/products/spices/cinnamon-detail.webp": {
    author: "Fumikas Sagisavas",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Cinnamon_sticks_(1).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Cinnamon_sticks_%281%29.jpg/1920px-Cinnamon_sticks_%281%29.jpg",
  },
  "/images/products/spices/cinnamon-ground.webp": {
    author: "Alabama Extension",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Cinnamon_(Alabama_Extension).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Cinnamon_%28Alabama_Extension%29.jpg/1920px-Cinnamon_%28Alabama_Extension%29.jpg",
  },
  "/images/products/spices/cinnamon-star-anise.webp": {
    author: "Kirsty Hughes kirstyhughes",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Fragrant_Spices_(Unsplash).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Fragrant_Spices_%28Unsplash%29.jpg/1920px-Fragrant_Spices_%28Unsplash%29.jpg",
  },
  "/images/products/spices/cinnamon-applications.webp": {
    author: "Andy Li",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Cinnamon_bun_-_Milfey_Patisserie_2026-08-31.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Cinnamon_bun_-_Milfey_Patisserie_2026-08-31.jpg/1920px-Cinnamon_bun_-_Milfey_Patisserie_2026-08-31.jpg",
  },
  "/images/products/spices/cinnamon-use-desserts.webp": {
    author: "Andy Li",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Apple_Crumble_%26_Custard_Tart_-_Caff%C3%A8_Nero_2025-09-14.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Apple_Crumble_%26_Custard_Tart_-_Caff%C3%A8_Nero_2025-09-14.jpg/1920px-Apple_Crumble_%26_Custard_Tart_-_Caff%C3%A8_Nero_2025-09-14.jpg",
  },
  "/images/products/spices/cinnamon-use-drinks.webp": {
    author: "Fg2",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Coffee_C0531.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Coffee_C0531.jpg/1920px-Coffee_C0531.jpg",
  },
  "/images/products/spices/cinnamon-use-savoury.webp": {
    author: "Miansari66",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Mattar_Pulao_(Peas_Pullao).JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Mattar_Pulao_%28Peas_Pullao%29.JPG/1920px-Mattar_Pulao_%28Peas_Pullao%29.JPG",
  },
  "/images/products/spices/cloves-hero.webp": {
    author: "Fumikas Sagisavas",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Dried_clove_sticks.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Dried_clove_sticks.jpg/1920px-Dried_clove_sticks.jpg",
  },
  "/images/products/spices/cloves-culinary-use.webp": {
    author: "Angela Huster",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Gl%C3%BChwein-Zubereitung.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Gl%C3%BChwein-Zubereitung.JPG/1920px-Gl%C3%BChwein-Zubereitung.JPG",
  },
  "/images/products/spices/coriander-seeds-hero.webp": {
    author: "Misterneedlemouse",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Whole_Coriander.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Whole_Coriander.jpg/1920px-Whole_Coriander.jpg",
  },
  "/images/products/spices/coriander-seeds-culinary-use.webp": {
    author: "Miansari66",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Coriander_whole.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Coriander_whole.jpg/1920px-Coriander_whole.jpg",
  },
  "/images/products/spices/coriander-seeds-use-baking.webp": {
    author: "Retired electrician",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Moscow,_Paveletskaya_Plaza_Feb.2025_-_store-baked_borodinsky_bread_02.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Moscow%2C_Paveletskaya_Plaza_Feb.2025_-_store-baked_borodinsky_bread_02.jpg/1920px-Moscow%2C_Paveletskaya_Plaza_Feb.2025_-_store-baked_borodinsky_bread_02.jpg",
  },
  "/images/products/spices/coriander-seeds-use-pickling.webp": {
    author: "Daderot",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Indian_mixed_pickles_-_Massachusetts.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Indian_mixed_pickles_-_Massachusetts.jpg/1920px-Indian_mixed_pickles_-_Massachusetts.jpg",
  },
  "/images/products/spices/coriander-seeds-use-rubs.webp": {
    author: "Herusutimbul",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Bumbu_Rawon.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Bumbu_Rawon.jpg/1920px-Bumbu_Rawon.jpg",
  },
  "/images/products/spices/cumin-seeds-hero.webp": {
    author: "Misterneedlemouse",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Whole_Cumin_Seeds.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Whole_Cumin_Seeds.jpg/1920px-Whole_Cumin_Seeds.jpg",
  },
  "/images/products/spices/cumin-seeds-applications.webp": {
    author: "Miansari66",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Sabut_Moong_Dal_Tadka_(Tarka).JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Sabut_Moong_Dal_Tadka_%28Tarka%29.JPG/1920px-Sabut_Moong_Dal_Tadka_%28Tarka%29.JPG",
  },
  "/images/products/spices/fennel-seeds-hero.webp": {
    author: "Holly Cheng",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    source: "https://commons.wikimedia.org/wiki/File:Fennel_seed.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Fennel_seed.jpg/1920px-Fennel_seed.jpg",
  },
  "/images/products/spices/fennel-seeds-plant.webp": {
    author: "Wouter Hagens",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Foeniculum_vulgare_A.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Foeniculum_vulgare_A.jpg/1920px-Foeniculum_vulgare_A.jpg",
  },
  "/images/products/spices/fennel-seeds-applications.webp": {
    author: "Connie Ma",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Fennel_seeds_and_rock_sugar,_Indian_aftermint.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Fennel_seeds_and_rock_sugar%2C_Indian_aftermint.jpg/1920px-Fennel_seeds_and_rock_sugar%2C_Indian_aftermint.jpg",
  },
  "/images/products/spices/fenugreek-seeds-hero.webp": {
    author: "Miansari66",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Fenugreek_seed.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Fenugreek_seed.JPG/1920px-Fenugreek_seed.JPG",
  },
  "/images/products/spices/fenugreek-seeds-applications.webp": {
    author: "Miansari66",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Mango_Pickle_Home_Made_Style.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Mango_Pickle_Home_Made_Style.JPG/1920px-Mango_Pickle_Home_Made_Style.JPG",
  },
  "/images/products/spices/green-cardamom-hero.webp": {
    author: "Misterneedlemouse",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Green_Cardamom_Pods.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Green_Cardamom_Pods.jpg/1920px-Green_Cardamom_Pods.jpg",
  },
  "/images/products/spices/green-cardamom-open-pod.webp": {
    author: "Nemo bis",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Green_cardamom_seeds.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Green_cardamom_seeds.JPG/1920px-Green_cardamom_seeds.JPG",
  },
  "/images/products/spices/green-cardamom-plant.webp": {
    author: "Chhe",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:ElettariaCardamomum.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/ElettariaCardamomum.jpg/1920px-ElettariaCardamomum.jpg",
  },
  "/images/products/spices/green-cardamom-applications.webp": {
    author: "Miansari66",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Masala_Chai.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Masala_Chai.JPG/1920px-Masala_Chai.JPG",
  },
  "/images/products/spices/mustard-seeds-hero.webp": {
    author: "Miansari66",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Mustard_black.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Mustard_black.JPG/1920px-Mustard_black.JPG",
  },
  "/images/products/spices/mustard-seeds-applications.webp": {
    author: "Rainer Zenz",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    source: "https://commons.wikimedia.org/wiki/File:Dijon_mustard_on_a_spoon_-_20051218.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Dijon_mustard_on_a_spoon_-_20051218.jpg/1920px-Dijon_mustard_on_a_spoon_-_20051218.jpg",
  },
  "/images/products/spices/psyllium-seed-hero.webp": {
    author: "مھتاب احمد سنڌي",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Raw_seed_of_psyllium.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Raw_seed_of_psyllium.jpg/1920px-Raw_seed_of_psyllium.jpg",
  },
  "/images/products/spices/psyllium-seed-applications.webp": {
    author: "Bastique (Cary Bass)",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Psyllium_seed_husk_pile.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Psyllium_seed_husk_pile.JPG/1920px-Psyllium_seed_husk_pile.JPG",
  },
  "/images/products/spices/red-chilli-hero.webp": {
    author: "qubodup",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Bouquet_of_Dried_Chili_Peppers_05.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Bouquet_of_Dried_Chili_Peppers_05.jpg/1920px-Bouquet_of_Dried_Chili_Peppers_05.jpg",
  },
  "/images/products/spices/red-chilli-applications.webp": {
    author: "Missvain",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Bangkok_9_-_July_2024_-_Sarah_Stierch_04.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Bangkok_9_-_July_2024_-_Sarah_Stierch_04.jpg/1920px-Bangkok_9_-_July_2024_-_Sarah_Stierch_04.jpg",
  },
  "/images/products/spices/turmeric-hero.webp": {
    author: "Rajasekhar1961",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Rythu_Vegetables_market,_Hyderabad_06.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Rythu_Vegetables_market%2C_Hyderabad_06.jpg/1920px-Rythu_Vegetables_market%2C_Hyderabad_06.jpg",
  },
  "/images/products/spices/turmeric-detail.webp": {
    author: "MattPicks",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Organic_Turmeric_Rhizome_(Root).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Organic_Turmeric_Rhizome_%28Root%29.jpg/1920px-Organic_Turmeric_Rhizome_%28Root%29.jpg",
  },
  "/images/products/spices/turmeric-culinary-use.webp": {
    author: "Daderot",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Yellow_curry_with_coconut,_chicken,_fingerling_potatoes,_fried_shallots,_and_basil_-_San_Francisco,_CA.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Yellow_curry_with_coconut%2C_chicken%2C_fingerling_potatoes%2C_fried_shallots%2C_and_basil_-_San_Francisco%2C_CA.jpg/1920px-Yellow_curry_with_coconut%2C_chicken%2C_fingerling_potatoes%2C_fried_shallots%2C_and_basil_-_San_Francisco%2C_CA.jpg",
  },
  "/images/products/spices/turmeric-use-drinks.webp": {
    author: "Andy Li",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Turmeric_Latte_-_T_@_The_Dials_2024-02-07.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Turmeric_Latte_-_T_%40_The_Dials_2024-02-07.jpg/1920px-Turmeric_Latte_-_T_%40_The_Dials_2024-02-07.jpg",
  },
  "/images/products/spices/turmeric-use-pickles.webp": {
    author: "Kandarpajit Kallol",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Lemon_Pickle_(Assamese_Nemur_Aachar).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Lemon_Pickle_%28Assamese_Nemur_Aachar%29.jpg/1920px-Lemon_Pickle_%28Assamese_Nemur_Aachar%29.jpg",
  },
  "/images/products/spices/turmeric-use-rice.webp": {
    author: "Mia Sulisnawati",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Nasi_Kuning_Behintalu.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Nasi_Kuning_Behintalu.jpg/1920px-Nasi_Kuning_Behintalu.jpg",
  },
  "/images/products/powders/black-pepper-powder-hero.webp": {
    author: "Nithyasrm",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Homemade_Pepper_powder.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Homemade_Pepper_powder.JPG/1920px-Homemade_Pepper_powder.JPG",
  },
  "/images/products/powders/black-pepper-powder-texture.webp": {
    author: "Eliška Jindříšková",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Ground_black_pepper.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Ground_black_pepper.jpg/1920px-Ground_black_pepper.jpg",
  },
  "/images/products/powders/black-pepper-powder-seasoning.webp": {
    author: "Daryn Nakhuda",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Applying_a_spice_rub_to_pork_ribs_for_a_barbecue_-_20080329.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Applying_a_spice_rub_to_pork_ribs_for_a_barbecue_-_20080329.jpg/1920px-Applying_a_spice_rub_to_pork_ribs_for_a_barbecue_-_20080329.jpg",
  },
  "/images/products/powders/black-pepper-powder-applications.webp": {
    author: "Popo le Chien",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Cacio_e_pepe.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Cacio_e_pepe.jpg/1920px-Cacio_e_pepe.jpg",
  },
  "/images/products/powders/clove-powder-hero.webp": {
    author: "Kitchenshaman",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Groundcloves.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Groundcloves.jpg",
    changes: "Cropped to remove a corner watermark.",
  },
  "/images/products/powders/clove-powder-applications.webp": {
    author: "freestocks.org from Olsztyn, Poland",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Gingerbread_cookies_and_milk_(31275892750).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Gingerbread_cookies_and_milk_%2831275892750%29.jpg/1920px-Gingerbread_cookies_and_milk_%2831275892750%29.jpg",
  },
  "/images/products/powders/coriander-seeds-powder-hero.webp": {
    author: "Nithyasrm",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Coriander_powder.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Coriander_powder.JPG/1920px-Coriander_powder.JPG",
  },
  "/images/products/powders/coriander-seeds-powder-blend.webp": {
    author: "Gaurav Dhwaj Khadka",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Coriander_Powder.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Coriander_Powder.jpg/1920px-Coriander_Powder.jpg",
  },
  "/images/products/powders/coriander-seeds-powder-applications.webp": {
    author: "Andy Li",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Chana_Masala_-_Mohammed_-_Spice_Of_Life_2024-05-27.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Chana_Masala_-_Mohammed_-_Spice_Of_Life_2024-05-27.jpg/1920px-Chana_Masala_-_Mohammed_-_Spice_Of_Life_2024-05-27.jpg",
  },
  "/images/products/powders/dry-ginger-powder-hero.webp": {
    author: "Piyush Kothari",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Dry_Ginger_1.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Dry_Ginger_1.jpg/1920px-Dry_Ginger_1.jpg",
  },
  "/images/products/powders/dry-ginger-powder-applications.webp": {
    author: "Samuel Wiki",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Arnott%27s_Ginger_Nut_03.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Arnott%27s_Ginger_Nut_03.jpg/1920px-Arnott%27s_Ginger_Nut_03.jpg",
  },
  "/images/products/powders/dry-mango-powder-applications.webp": {
    author: "stu_spivack",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Indian_cuisine-Chaat-Bhelpuri-03.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Indian_cuisine-Chaat-Bhelpuri-03.jpg/1920px-Indian_cuisine-Chaat-Bhelpuri-03.jpg",
  },
  "/images/products/powders/garam-masala-hero.webp": {
    author: "Gaurav Dhwaj Khadka",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Garam_Masala_1.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Garam_Masala_1.jpg/1920px-Garam_Masala_1.jpg",
  },
  "/images/products/powders/garam-masala-whole-spices.webp": {
    author: "Miansari66",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Garam_Masala.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Garam_Masala.JPG/1920px-Garam_Masala.JPG",
  },
  "/images/products/powders/garam-masala-curry.webp": {
    author: "Abhilashsnair",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Chicken_curry_Trivandrum.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Chicken_curry_Trivandrum.jpg/1920px-Chicken_curry_Trivandrum.jpg",
  },
  "/images/products/powders/garlic-powder-hero.webp": {
    author: "John Phelan",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Garlic_Powder,_Penzeys_Spices,_Arlington_Heights_MA.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Garlic_Powder%2C_Penzeys_Spices%2C_Arlington_Heights_MA.jpg/1920px-Garlic_Powder%2C_Penzeys_Spices%2C_Arlington_Heights_MA.jpg",
  },
  "/images/products/powders/garlic-powder-applications.webp": {
    author: "Goose Green Photography",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Putting_garlic_powder_on_some_cooked_potatoes.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Putting_garlic_powder_on_some_cooked_potatoes.jpg/1920px-Putting_garlic_powder_on_some_cooked_potatoes.jpg",
  },
  "/images/products/powders/nutmeg-powder-hero.webp": {
    author: "Dominikmatus",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Nutmeg-spice.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Nutmeg-spice.jpg/1920px-Nutmeg-spice.jpg",
  },
  "/images/products/powders/nutmeg-powder-applications.webp": {
    author: "Missvain",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Eggnog_at_Patrona_-_December_2023_-_Sarah_Stierch_02.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Eggnog_at_Patrona_-_December_2023_-_Sarah_Stierch_02.jpg/1920px-Eggnog_at_Patrona_-_December_2023_-_Sarah_Stierch_02.jpg",
  },
  "/images/products/powders/nutmeg-powder-fruit.webp": {
    author: "Schlawensko",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Nutmeg_fruit_with_mace.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Nutmeg_fruit_with_mace.jpg/1920px-Nutmeg_fruit_with_mace.jpg",
  },
  "/images/products/powders/nutmeg-powder-kernels.webp": {
    author: "Misterneedlemouse",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Whole_Nutmeg.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Whole_Nutmeg.jpg/1920px-Whole_Nutmeg.jpg",
  },
  "/images/products/powders/white-pepper-powder-hero.webp": {
    author: "Susan Slater",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:White_pepper_(ground).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/White_pepper_%28ground%29.jpg/1920px-White_pepper_%28ground%29.jpg",
  },
  "/images/products/powders/white-pepper-powder-applications.webp": {
    author: "Yausheungbon",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:HK_Sheung_Wan_Daimond_Club_Restaurant_food_%E8%83%A1%E6%A4%92%E7%B2%89_White_pepper_%E7%9A%AE%E8%9B%8B%E7%98%A6%E8%82%89%E7%B2%A5_Century_Egg_Congee_May-2012.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/HK_Sheung_Wan_Daimond_Club_Restaurant_food_%E8%83%A1%E6%A4%92%E7%B2%89_White_pepper_%E7%9A%AE%E8%9B%8B%E7%98%A6%E8%82%89%E7%B2%A5_Century_Egg_Congee_May-2012.JPG/1920px-HK_Sheung_Wan_Daimond_Club_Restaurant_food_%E8%83%A1%E6%A4%92%E7%B2%89_White_pepper_%E7%9A%AE%E8%9B%8B%E7%98%A6%E8%82%89%E7%B2%A5_Century_Egg_Congee_May-2012.JPG",
  },
};
