/**
 * Sources of the site's third-party photographs (product pages and Blog
 * articles), keyed by their public path. Each is a real photograph from
 * Wikimedia Commons, downloaded once (1920 px max, WebP) and served from
 * this site: Commons rate-limits server-side image fetches, so hotlinking
 * is not reliable.
 *
 * Every file is credited (author, source, licence) on /image-credits, as
 * CC BY and CC BY-SA require; CC0 and public-domain files are listed too.
 */

/** Where a licensed third-party photograph came from, and the terms it is used under. */
export type PhotoCredit = {
  author: string;
  license: string;
  licenseUrl?: string;
  /** The file's description page (licence, author and history). */
  source: string;
  /** The direct image URL the local copy was downloaded from. */
  original: string;
  /** Any edit beyond resizing and WebP conversion. */
  changes?: string;
};

export const productPhotoCredits: Record<string, PhotoCredit> = {
  "/images/products/agri/mango/mango-hero.webp": {
    author: "Hajia Hijjah",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Ripe_fresh_mangoes.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Ripe_fresh_mangoes.jpg/1920px-Ripe_fresh_mangoes.jpg",
  },
  "/images/products/agri/mango/mango-use-fresh.webp": {
    author: "SarKaLay စာကလေး",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Ripe_mango_(23173).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Ripe_mango_%2823173%29.jpg/1920px-Ripe_mango_%2823173%29.jpg",
  },
  "/images/products/agri/mango/mango-use-drinks.webp": {
    author: "CYAN",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mango_juice_a0.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Mango_juice_a0.jpg/1920px-Mango_juice_a0.jpg",
  },
  "/images/products/agri/mango/mango-use-processing.webp": {
    author: "Gaurav Dhwaj Khadka",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Mango_pulp.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Mango_pulp.jpg/1920px-Mango_pulp.jpg",
  },
  "/images/products/agri/mango/mango-use-desserts.webp": {
    author: "Subhransuphotography",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mango_Custard-Puri_Odisha-IMG_1041.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Mango_Custard-Puri_Odisha-IMG_1041.jpg/1920px-Mango_Custard-Puri_Odisha-IMG_1041.jpg",
  },
  "/images/products/agri/banana/banana-hero.webp": {
    author: "Wilfredor",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Cavendish_banana_from_Maracaibo.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Cavendish_banana_from_Maracaibo.jpg/1920px-Cavendish_banana_from_Maracaibo.jpg",
  },
  "/images/products/agri/banana/banana-detail.webp": {
    author: "Noblevmy at Malayalam Wikipedia",
    license: "CC BY 2.5",
    licenseUrl: "https://creativecommons.org/licenses/by/2.5",
    source: "https://commons.wikimedia.org/wiki/File:Kadalikkula.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Kadalikkula.JPG/1920px-Kadalikkula.JPG",
  },
  "/images/products/agri/grapes/grapes-hero.webp": {
    author: "Anna.Massini",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Grappolo_di_uva_nera.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Grappolo_di_uva_nera.jpg/1920px-Grappolo_di_uva_nera.jpg",
  },
  "/images/products/agri/grapes/grapes-detail.webp": {
    author: "Krzysztof Golik",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Vine_in_the_vineyard_in_Kaysersberg.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Vine_in_the_vineyard_in_Kaysersberg.jpg/1920px-Vine_in_the_vineyard_in_Kaysersberg.jpg",
  },
  "/images/products/agri/grapes/grapes-green.webp": {
    author: "Fumikas Sagisavas",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Green_grapes_(20240716).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Green_grapes_%2820240716%29.jpg/1920px-Green_grapes_%2820240716%29.jpg",
  },
  "/images/products/agri/pomegranate/pomegranate-hero.webp": {
    author: "Rhododendrites",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Pomegranate_on_white.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Pomegranate_on_white.jpg/1920px-Pomegranate_on_white.jpg",
  },
  "/images/products/agri/pomegranate/pomegranate-detail.webp": {
    author: "Ivar Leidus",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Pomegranate_(opened).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Pomegranate_%28opened%29.jpg/1920px-Pomegranate_%28opened%29.jpg",
  },
  "/images/products/agri/pomegranate/pomegranate-use-fresh.webp": {
    author: "Ivar Leidus",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Pomegranate_fruit_-_whole_and_piece_with_arils.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Pomegranate_fruit_-_whole_and_piece_with_arils.jpg/1920px-Pomegranate_fruit_-_whole_and_piece_with_arils.jpg",
  },
  "/images/products/agri/pomegranate/pomegranate-use-salad.webp": {
    author: "dnm",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Fruktsallad_(Fruit_salad).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/7/74/Fruktsallad_%28Fruit_salad%29.jpg",
  },
  "/images/products/agri/pomegranate/pomegranate-use-juice.webp": {
    author: "Augustus Binu",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Pomegranate_juice_with_slice.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Pomegranate_juice_with_slice.jpg/1920px-Pomegranate_juice_with_slice.jpg",
  },
  "/images/products/agri/pomegranate/pomegranate-use-processing.webp": {
    author: "HaJunkiyada",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Liat_Portal_for_Foodie_Disorder_-_Pomegranate_Seeds.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Liat_Portal_for_Foodie_Disorder_-_Pomegranate_Seeds.jpg/1920px-Liat_Portal_for_Foodie_Disorder_-_Pomegranate_Seeds.jpg",
  },
  "/images/products/agri/orange/orange-hero.webp": {
    author: "USDA Agricultural Research Service",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Ambersweet_oranges.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Ambersweet_oranges.jpg/1920px-Ambersweet_oranges.jpg",
  },
  "/images/products/agri/orange/orange-detail.webp": {
    author: "Scott Bauer, USDA Agricultural Research Service",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Oranges_and_orange_juice.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/5/5a/Oranges_and_orange_juice.jpg",
  },
  "/images/products/agri/orange/orange-slice.webp": {
    author: "Evan-Amos",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Orange-Fruit-Pieces.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Orange-Fruit-Pieces.jpg/1920px-Orange-Fruit-Pieces.jpg",
  },
  "/images/products/agri/orange/orange-tree.webp": {
    author: "Zeynel Cebeci",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Local_Orange_Variety_of_Kozan_-_Kozan_Yerli_Portakal_04.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Local_Orange_Variety_of_Kozan_-_Kozan_Yerli_Portakal_04.jpg/1920px-Local_Orange_Variety_of_Kozan_-_Kozan_Yerli_Portakal_04.jpg",
  },
  "/images/products/agri/chikoo/chikoo-hero.webp": {
    author: "KIRUTHIKA OFF",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Sapodilla_fruit_image.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Sapodilla_fruit_image.jpg/1920px-Sapodilla_fruit_image.jpg",
  },
  "/images/products/agri/chikoo/chikoo-detail.webp": {
    author: "Kristof Zyskowski & Yulia Bereshpolova",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Sapotaceae-_Manilkara_zapota_(sapodilla).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Sapotaceae-_Manilkara_zapota_%28sapodilla%29.jpg/1920px-Sapotaceae-_Manilkara_zapota_%28sapodilla%29.jpg",
  },
  "/images/products/agri/papaya/papaya-hero.webp": {
    author: "Ivar Leidus",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Papaya_-_longitudinal_section.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Papaya_-_longitudinal_section.jpg/1920px-Papaya_-_longitudinal_section.jpg",
  },
  "/images/products/agri/papaya/papaya-detail.webp": {
    author: "Gerda Arendt",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Papaya_fruits_on_tree,_San_Andres.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Papaya_fruits_on_tree%2C_San_Andres.jpg/1920px-Papaya_fruits_on_tree%2C_San_Andres.jpg",
  },
  "/images/products/agri/papaya/papaya-use-fresh.webp": {
    author: "Billjones94",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Longitudinal_section_of_ripe_papaya_fruit_in_West_Bengal,_India.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Longitudinal_section_of_ripe_papaya_fruit_in_West_Bengal%2C_India.jpg/1920px-Longitudinal_section_of_ripe_papaya_fruit_in_West_Bengal%2C_India.jpg",
  },
  "/images/products/agri/papaya/papaya-use-drinks.webp": {
    author: "El Mono Español",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Batido_de_papaya.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Batido_de_papaya.jpg/1920px-Batido_de_papaya.jpg",
  },
  "/images/products/agri/papaya/papaya-use-salad.webp": {
    author: "Vee Satayamas",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Blue_crab_papaya_salad,_Ban-kru-eed,_Rayong.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Blue_crab_papaya_salad%2C_Ban-kru-eed%2C_Rayong.jpg/1920px-Blue_crab_papaya_salad%2C_Ban-kru-eed%2C_Rayong.jpg",
  },
  "/images/products/agri/papaya/papaya-use-processing.webp": {
    author: "Evening42",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Papaya_cubes.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Papaya_cubes.jpg/1920px-Papaya_cubes.jpg",
  },
  "/images/products/agri/guava/guava-hero.webp": {
    author: "Thamizhpparithi Maari",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Guava_-_Psidium_guajava_fruit_of_Tamilnadu.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Guava_-_Psidium_guajava_fruit_of_Tamilnadu.jpg/1920px-Guava_-_Psidium_guajava_fruit_of_Tamilnadu.jpg",
  },
  "/images/products/agri/guava/guava-detail.webp": {
    author: "NanaYawBotar",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Unripe_guava_fruit.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/e/ee/Unripe_guava_fruit.jpg",
  },
  "/images/products/agri/guava/guava-slice.webp": {
    author: "Hungda",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:%E1%BB%94i_%C4%91%C3%A0o_-pink_guava.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/4/40/%E1%BB%94i_%C4%91%C3%A0o_-pink_guava.jpg",
  },
  "/images/products/agri/guava/guava-white.webp": {
    author: "GTSPACE",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:GUAVA_FRUIT.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/GUAVA_FRUIT.jpg/1920px-GUAVA_FRUIT.jpg",
  },
  "/images/products/agri/beans/beans-blanched.webp": {
    author: "Alabama Extension",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Green_Beans_(Alabama_Extension).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Green_Beans_%28Alabama_Extension%29.jpg/1920px-Green_Beans_%28Alabama_Extension%29.jpg",
  },
  "/images/products/agri/beans/beans-bowl.webp": {
    author: "www.Pixel.la Free Stock Photos",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Green_beans_in_a_wooden_box.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Green_beans_in_a_wooden_box.jpg/1920px-Green_beans_in_a_wooden_box.jpg",
  },
  "/images/products/agri/beans/beans-detail.webp": {
    author: "Jeffery Martin",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Green_beans_in_a_pile.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Green_beans_in_a_pile.JPG/1920px-Green_beans_in_a_pile.JPG",
  },
  "/images/products/agri/beans/beans-hero.webp": {
    author: "Gaurav Dhwaj Khadka",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Green_Beans_1.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Green_Beans_1.jpg/1920px-Green_Beans_1.jpg",
  },
  "/images/products/agri/bitter-gourd/bitter-gourd-detail.webp": {
    author: "စာကလေး SarKaLay",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:%E1%80%80%E1%80%BC%E1%80%80%E1%80%BA%E1%80%9F%E1%80%84%E1%80%BA%E1%80%B8%E1%80%81%E1%80%AB%E1%80%B8%E1%80%9E%E1%80%AE%E1%80%B8_Bitter_Melon.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/%E1%80%80%E1%80%BC%E1%80%80%E1%80%BA%E1%80%9F%E1%80%84%E1%80%BA%E1%80%B8%E1%80%81%E1%80%AB%E1%80%B8%E1%80%9E%E1%80%AE%E1%80%B8_Bitter_Melon.jpg/1920px-%E1%80%80%E1%80%BC%E1%80%80%E1%80%BA%E1%80%9F%E1%80%84%E1%80%BA%E1%80%B8%E1%80%81%E1%80%AB%E1%80%B8%E1%80%9E%E1%80%AE%E1%80%B8_Bitter_Melon.jpg",
  },
  "/images/products/agri/bitter-gourd/bitter-gourd-hero.webp": {
    author: "Bhaskaranaidu",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Bitter_gourd_at_Hyderabad_market.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Bitter_gourd_at_Hyderabad_market.jpg/1920px-Bitter_gourd_at_Hyderabad_market.jpg",
  },
  "/images/products/agri/drumstick/drumstick-hero.webp": {
    author: "David E Mead",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Ben-oil_tree_pods_(marketed)_2.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Ben-oil_tree_pods_%28marketed%29_2.jpg/1920px-Ben-oil_tree_pods_%28marketed%29_2.jpg",
  },
  "/images/products/agri/drumstick/drumstick-use-curry.webp": {
    author: "Anamika mathur",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Laajawaab_Drumstick_Curry.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Laajawaab_Drumstick_Curry.jpg/1280px-Laajawaab_Drumstick_Curry.jpg",
  },
  "/images/products/agri/drumstick/drumstick-use-frozen.webp": {
    author: "Judgefloro",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:2301Moringa_oleifera_pod_(seedpod)_textures_37.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/2301Moringa_oleifera_pod_%28seedpod%29_textures_37.jpg/1920px-2301Moringa_oleifera_pod_%28seedpod%29_textures_37.jpg",
  },
  "/images/products/agri/drumstick/drumstick-use-sambar.webp": {
    author: "Booradleyp1",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Sambar_(drumstick).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Sambar_%28drumstick%29.jpg/1920px-Sambar_%28drumstick%29.jpg",
  },
  "/images/products/agri/drumstick/drumstick-use-soup.webp": {
    author: "Wagaung",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    source: "https://commons.wikimedia.org/wiki/File:Dunt-dalun_chin-yei_1760.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/4/41/Dunt-dalun_chin-yei_1760.JPG",
  },
  "/images/products/agri/eggplant/eggplant-detail.webp": {
    author: "Karen and Brad Emerson",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Eggplant_(27751779984).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Eggplant_%2827751779984%29.jpg/1920px-Eggplant_%2827751779984%29.jpg",
  },
  "/images/products/agri/eggplant/eggplant-hero.webp": {
    author: "Fumikas Sagisavas",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Round_eggplant_(2).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Round_eggplant_%282%29.jpg/1920px-Round_eggplant_%282%29.jpg",
  },
  "/images/products/agri/frozen-peas/frozen-peas-detail.webp": {
    author: "Paul Wilkinson",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Frozen_Peas_(8042519481).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Frozen_Peas_%288042519481%29.jpg/1920px-Frozen_Peas_%288042519481%29.jpg",
  },
  "/images/products/agri/frozen-peas/frozen-peas-hero.webp": {
    author: "Jina Lee",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    source: "https://commons.wikimedia.org/wiki/File:Frozen_peas.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Frozen_peas.JPG/1920px-Frozen_peas.JPG",
  },
  "/images/products/agri/frozen-peas/frozen-peas-pods.webp": {
    author: "Fumikas Sagisavas",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Green_pea_pods.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Green_pea_pods.jpg/1920px-Green_pea_pods.jpg",
  },
  "/images/products/agri/frozen-peas/frozen-peas-scoop.webp": {
    author: "Ruth Hartnup",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Peas_(484346231).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Peas_%28484346231%29.jpg/1920px-Peas_%28484346231%29.jpg",
  },
  "/images/products/agri/okra/okra-hero.webp": {
    author: "စာကလေး",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Okra_Ron-Pa-Ti-Tee.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Okra_Ron-Pa-Ti-Tee.jpg/1920px-Okra_Ron-Pa-Ti-Tee.jpg",
  },
  "/images/products/agri/okra/okra-use-curry.webp": {
    author: "やましこ",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Bhindi_masala_(49657981033).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Bhindi_masala_%2849657981033%29.jpg/1920px-Bhindi_masala_%2849657981033%29.jpg",
  },
  "/images/products/agri/okra/okra-use-fried.webp": {
    author: "Ashwani Singh",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Karari_bhindi_!!!.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Karari_bhindi_%21%21%21.jpg/1920px-Karari_bhindi_%21%21%21.jpg",
  },
  "/images/products/agri/okra/okra-use-frozen.webp": {
    author: "Alabama Extension",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Frozen_Okra.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Frozen_Okra.jpg/1920px-Frozen_Okra.jpg",
  },
  "/images/products/agri/okra/okra-use-stew.webp": {
    author: "Benoît Prieur",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Du_bamia_avec_du_riz_en_f%C3%A9vrier_2022.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Du_bamia_avec_du_riz_en_f%C3%A9vrier_2022.jpg/1920px-Du_bamia_avec_du_riz_en_f%C3%A9vrier_2022.jpg",
  },
  "/images/products/spices/black-pepper-hero.webp": {
    author: "Misterneedlemouse",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Tellicherry_Black_Peppercorns.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Tellicherry_Black_Peppercorns.jpg/1920px-Tellicherry_Black_Peppercorns.jpg",
  },
  "/images/products/spices/black-pepper-vine.webp": {
    author: "Ronambiar",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Piper_nigrum_2.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Piper_nigrum_2.jpg/1920px-Piper_nigrum_2.jpg",
  },
  "/images/products/spices/black-pepper-culinary-use.webp": {
    author: "Daderot",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Steak_and_asparagus_on_peas,_with_olive_oil_and_black_pepper_-_Massachusetts.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Steak_and_asparagus_on_peas%2C_with_olive_oil_and_black_pepper_-_Massachusetts.jpg/1920px-Steak_and_asparagus_on_peas%2C_with_olive_oil_and_black_pepper_-_Massachusetts.jpg",
  },
  "/images/products/spices/cinnamon-hero.webp": {
    author: "Fumikas Sagisavas",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Cinnamon_sticks_(3).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Cinnamon_sticks_%283%29.jpg/1920px-Cinnamon_sticks_%283%29.jpg",
  },
  "/images/products/spices/cinnamon-detail.webp": {
    author: "Fumikas Sagisavas",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Cinnamon_sticks_(1).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Cinnamon_sticks_%281%29.jpg/1920px-Cinnamon_sticks_%281%29.jpg",
  },
  "/images/products/spices/cinnamon-ground.webp": {
    author: "Alabama Extension",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Cinnamon_(Alabama_Extension).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Cinnamon_%28Alabama_Extension%29.jpg/1920px-Cinnamon_%28Alabama_Extension%29.jpg",
  },
  "/images/products/spices/cinnamon-star-anise.webp": {
    author: "Kirsty Hughes kirstyhughes",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Fragrant_Spices_(Unsplash).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Fragrant_Spices_%28Unsplash%29.jpg/1920px-Fragrant_Spices_%28Unsplash%29.jpg",
  },
  "/images/products/spices/cinnamon-applications.webp": {
    author: "Andy Li",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Cinnamon_bun_-_Milfey_Patisserie_2026-08-31.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Cinnamon_bun_-_Milfey_Patisserie_2026-08-31.jpg/1920px-Cinnamon_bun_-_Milfey_Patisserie_2026-08-31.jpg",
  },
  "/images/products/spices/cinnamon-use-desserts.webp": {
    author: "Andy Li",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Apple_Crumble_%26_Custard_Tart_-_Caff%C3%A8_Nero_2025-09-14.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Apple_Crumble_%26_Custard_Tart_-_Caff%C3%A8_Nero_2025-09-14.jpg/1920px-Apple_Crumble_%26_Custard_Tart_-_Caff%C3%A8_Nero_2025-09-14.jpg",
  },
  "/images/products/spices/cinnamon-use-drinks.webp": {
    author: "Fg2",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Coffee_C0531.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Coffee_C0531.jpg/1920px-Coffee_C0531.jpg",
  },
  "/images/products/spices/cinnamon-use-savoury.webp": {
    author: "Miansari66",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Mattar_Pulao_(Peas_Pullao).JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Mattar_Pulao_%28Peas_Pullao%29.JPG/1920px-Mattar_Pulao_%28Peas_Pullao%29.JPG",
  },
  "/images/products/spices/cloves-hero.webp": {
    author: "Fumikas Sagisavas",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Dried_clove_sticks.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Dried_clove_sticks.jpg/1920px-Dried_clove_sticks.jpg",
  },
  "/images/products/spices/cloves-culinary-use.webp": {
    author: "Angela Huster",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Gl%C3%BChwein-Zubereitung.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Gl%C3%BChwein-Zubereitung.JPG/1920px-Gl%C3%BChwein-Zubereitung.JPG",
  },
  "/images/products/spices/coriander-seeds-hero.webp": {
    author: "Misterneedlemouse",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Whole_Coriander.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Whole_Coriander.jpg/1920px-Whole_Coriander.jpg",
  },
  "/images/products/spices/coriander-seeds-culinary-use.webp": {
    author: "Miansari66",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Coriander_whole.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Coriander_whole.jpg/1920px-Coriander_whole.jpg",
  },
  "/images/products/spices/coriander-seeds-use-baking.webp": {
    author: "Retired electrician",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Moscow,_Paveletskaya_Plaza_Feb.2025_-_store-baked_borodinsky_bread_02.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Moscow%2C_Paveletskaya_Plaza_Feb.2025_-_store-baked_borodinsky_bread_02.jpg/1920px-Moscow%2C_Paveletskaya_Plaza_Feb.2025_-_store-baked_borodinsky_bread_02.jpg",
  },
  "/images/products/spices/coriander-seeds-use-pickling.webp": {
    author: "Daderot",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Indian_mixed_pickles_-_Massachusetts.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Indian_mixed_pickles_-_Massachusetts.jpg/1920px-Indian_mixed_pickles_-_Massachusetts.jpg",
  },
  "/images/products/spices/coriander-seeds-use-rubs.webp": {
    author: "Herusutimbul",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Bumbu_Rawon.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Bumbu_Rawon.jpg/1920px-Bumbu_Rawon.jpg",
  },
  "/images/products/spices/cumin-seeds-hero.webp": {
    author: "Misterneedlemouse",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Whole_Cumin_Seeds.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Whole_Cumin_Seeds.jpg/1920px-Whole_Cumin_Seeds.jpg",
  },
  "/images/products/spices/cumin-seeds-applications.webp": {
    author: "Miansari66",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Sabut_Moong_Dal_Tadka_(Tarka).JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Sabut_Moong_Dal_Tadka_%28Tarka%29.JPG/1920px-Sabut_Moong_Dal_Tadka_%28Tarka%29.JPG",
  },
  "/images/products/spices/fennel-seeds-hero.webp": {
    author: "Holly Cheng",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    source: "https://commons.wikimedia.org/wiki/File:Fennel_seed.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Fennel_seed.jpg/1920px-Fennel_seed.jpg",
  },
  "/images/products/spices/fennel-seeds-plant.webp": {
    author: "Wouter Hagens",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Foeniculum_vulgare_A.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Foeniculum_vulgare_A.jpg/1920px-Foeniculum_vulgare_A.jpg",
  },
  "/images/products/spices/fennel-seeds-applications.webp": {
    author: "Connie Ma",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Fennel_seeds_and_rock_sugar,_Indian_aftermint.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Fennel_seeds_and_rock_sugar%2C_Indian_aftermint.jpg/1920px-Fennel_seeds_and_rock_sugar%2C_Indian_aftermint.jpg",
  },
  "/images/products/spices/fenugreek-seeds-hero.webp": {
    author: "Miansari66",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Fenugreek_seed.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Fenugreek_seed.JPG/1920px-Fenugreek_seed.JPG",
  },
  "/images/products/spices/fenugreek-seeds-applications.webp": {
    author: "Miansari66",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Mango_Pickle_Home_Made_Style.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Mango_Pickle_Home_Made_Style.JPG/1920px-Mango_Pickle_Home_Made_Style.JPG",
  },
  "/images/products/spices/green-cardamom-hero.webp": {
    author: "Misterneedlemouse",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Green_Cardamom_Pods.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Green_Cardamom_Pods.jpg/1920px-Green_Cardamom_Pods.jpg",
  },
  "/images/products/spices/green-cardamom-open-pod.webp": {
    author: "Nemo bis",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Green_cardamom_seeds.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Green_cardamom_seeds.JPG/1920px-Green_cardamom_seeds.JPG",
  },
  "/images/products/spices/green-cardamom-plant.webp": {
    author: "Chhe",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:ElettariaCardamomum.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/ElettariaCardamomum.jpg/1920px-ElettariaCardamomum.jpg",
  },
  "/images/products/spices/green-cardamom-applications.webp": {
    author: "Miansari66",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Masala_Chai.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Masala_Chai.JPG/1920px-Masala_Chai.JPG",
  },
  "/images/products/spices/mustard-seeds-hero.webp": {
    author: "Miansari66",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Mustard_black.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Mustard_black.JPG/1920px-Mustard_black.JPG",
  },
  "/images/products/spices/mustard-seeds-applications.webp": {
    author: "Rainer Zenz",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    source: "https://commons.wikimedia.org/wiki/File:Dijon_mustard_on_a_spoon_-_20051218.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Dijon_mustard_on_a_spoon_-_20051218.jpg/1920px-Dijon_mustard_on_a_spoon_-_20051218.jpg",
  },
  "/images/products/spices/psyllium-seed-hero.webp": {
    author: "مھتاب احمد سنڌي",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Raw_seed_of_psyllium.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Raw_seed_of_psyllium.jpg/1920px-Raw_seed_of_psyllium.jpg",
  },
  "/images/products/spices/psyllium-seed-applications.webp": {
    author: "Bastique (Cary Bass)",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Psyllium_seed_husk_pile.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Psyllium_seed_husk_pile.JPG/1920px-Psyllium_seed_husk_pile.JPG",
  },
  "/images/products/spices/red-chilli-hero.webp": {
    author: "qubodup",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Bouquet_of_Dried_Chili_Peppers_05.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Bouquet_of_Dried_Chili_Peppers_05.jpg/1920px-Bouquet_of_Dried_Chili_Peppers_05.jpg",
  },
  "/images/products/spices/red-chilli-applications.webp": {
    author: "Missvain",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Bangkok_9_-_July_2024_-_Sarah_Stierch_04.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Bangkok_9_-_July_2024_-_Sarah_Stierch_04.jpg/1920px-Bangkok_9_-_July_2024_-_Sarah_Stierch_04.jpg",
  },
  "/images/products/spices/turmeric-hero.webp": {
    author: "Rajasekhar1961",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Rythu_Vegetables_market,_Hyderabad_06.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Rythu_Vegetables_market%2C_Hyderabad_06.jpg/1920px-Rythu_Vegetables_market%2C_Hyderabad_06.jpg",
  },
  "/images/products/spices/turmeric-detail.webp": {
    author: "MattPicks",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Organic_Turmeric_Rhizome_(Root).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Organic_Turmeric_Rhizome_%28Root%29.jpg/1920px-Organic_Turmeric_Rhizome_%28Root%29.jpg",
  },
  "/images/products/spices/turmeric-culinary-use.webp": {
    author: "Daderot",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Yellow_curry_with_coconut,_chicken,_fingerling_potatoes,_fried_shallots,_and_basil_-_San_Francisco,_CA.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Yellow_curry_with_coconut%2C_chicken%2C_fingerling_potatoes%2C_fried_shallots%2C_and_basil_-_San_Francisco%2C_CA.jpg/1920px-Yellow_curry_with_coconut%2C_chicken%2C_fingerling_potatoes%2C_fried_shallots%2C_and_basil_-_San_Francisco%2C_CA.jpg",
  },
  "/images/products/spices/turmeric-use-drinks.webp": {
    author: "Andy Li",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Turmeric_Latte_-_T_@_The_Dials_2024-02-07.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Turmeric_Latte_-_T_%40_The_Dials_2024-02-07.jpg/1920px-Turmeric_Latte_-_T_%40_The_Dials_2024-02-07.jpg",
  },
  "/images/products/spices/turmeric-use-pickles.webp": {
    author: "Kandarpajit Kallol",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Lemon_Pickle_(Assamese_Nemur_Aachar).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Lemon_Pickle_%28Assamese_Nemur_Aachar%29.jpg/1920px-Lemon_Pickle_%28Assamese_Nemur_Aachar%29.jpg",
  },
  "/images/products/spices/turmeric-use-rice.webp": {
    author: "Mia Sulisnawati",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Nasi_Kuning_Behintalu.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Nasi_Kuning_Behintalu.jpg/1920px-Nasi_Kuning_Behintalu.jpg",
  },
  "/images/products/powders/black-pepper-powder-hero.webp": {
    author: "Nithyasrm",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Homemade_Pepper_powder.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Homemade_Pepper_powder.JPG/1920px-Homemade_Pepper_powder.JPG",
  },
  "/images/products/powders/black-pepper-powder-texture.webp": {
    author: "Eliška Jindříšková",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Ground_black_pepper.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Ground_black_pepper.jpg/1920px-Ground_black_pepper.jpg",
  },
  "/images/products/powders/black-pepper-powder-seasoning.webp": {
    author: "Daryn Nakhuda",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Applying_a_spice_rub_to_pork_ribs_for_a_barbecue_-_20080329.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Applying_a_spice_rub_to_pork_ribs_for_a_barbecue_-_20080329.jpg/1920px-Applying_a_spice_rub_to_pork_ribs_for_a_barbecue_-_20080329.jpg",
  },
  "/images/products/powders/black-pepper-powder-applications.webp": {
    author: "Popo le Chien",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Cacio_e_pepe.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Cacio_e_pepe.jpg/1920px-Cacio_e_pepe.jpg",
  },
  "/images/products/powders/clove-powder-hero.webp": {
    author: "Kitchenshaman",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Groundcloves.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Groundcloves.jpg",
    changes: "Cropped to remove a corner watermark.",
  },
  "/images/products/powders/clove-powder-applications.webp": {
    author: "freestocks.org from Olsztyn, Poland",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Gingerbread_cookies_and_milk_(31275892750).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Gingerbread_cookies_and_milk_%2831275892750%29.jpg/1920px-Gingerbread_cookies_and_milk_%2831275892750%29.jpg",
  },
  "/images/products/powders/coriander-seeds-powder-hero.webp": {
    author: "Nithyasrm",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Coriander_powder.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Coriander_powder.JPG/1920px-Coriander_powder.JPG",
  },
  "/images/products/powders/coriander-seeds-powder-blend.webp": {
    author: "Gaurav Dhwaj Khadka",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Coriander_Powder.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Coriander_Powder.jpg/1920px-Coriander_Powder.jpg",
  },
  "/images/products/powders/coriander-seeds-powder-applications.webp": {
    author: "Andy Li",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Chana_Masala_-_Mohammed_-_Spice_Of_Life_2024-05-27.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Chana_Masala_-_Mohammed_-_Spice_Of_Life_2024-05-27.jpg/1920px-Chana_Masala_-_Mohammed_-_Spice_Of_Life_2024-05-27.jpg",
  },
  "/images/products/powders/dry-ginger-powder-hero.webp": {
    author: "Piyush Kothari",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Dry_Ginger_1.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Dry_Ginger_1.jpg/1920px-Dry_Ginger_1.jpg",
  },
  "/images/products/powders/dry-ginger-powder-applications.webp": {
    author: "Samuel Wiki",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Arnott%27s_Ginger_Nut_03.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Arnott%27s_Ginger_Nut_03.jpg/1920px-Arnott%27s_Ginger_Nut_03.jpg",
  },
  "/images/products/powders/dry-mango-powder-applications.webp": {
    author: "stu_spivack",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Indian_cuisine-Chaat-Bhelpuri-03.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Indian_cuisine-Chaat-Bhelpuri-03.jpg/1920px-Indian_cuisine-Chaat-Bhelpuri-03.jpg",
  },
  "/images/products/powders/garam-masala-hero.webp": {
    author: "Gaurav Dhwaj Khadka",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Garam_Masala_1.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Garam_Masala_1.jpg/1920px-Garam_Masala_1.jpg",
  },
  "/images/products/powders/garam-masala-whole-spices.webp": {
    author: "Miansari66",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Garam_Masala.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Garam_Masala.JPG/1920px-Garam_Masala.JPG",
  },
  "/images/products/powders/garam-masala-curry.webp": {
    author: "Abhilashsnair",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Chicken_curry_Trivandrum.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Chicken_curry_Trivandrum.jpg/1920px-Chicken_curry_Trivandrum.jpg",
  },
  "/images/products/powders/garlic-powder-hero.webp": {
    author: "John Phelan",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Garlic_Powder,_Penzeys_Spices,_Arlington_Heights_MA.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Garlic_Powder%2C_Penzeys_Spices%2C_Arlington_Heights_MA.jpg/1920px-Garlic_Powder%2C_Penzeys_Spices%2C_Arlington_Heights_MA.jpg",
  },
  "/images/products/powders/garlic-powder-applications.webp": {
    author: "Goose Green Photography",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Putting_garlic_powder_on_some_cooked_potatoes.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Putting_garlic_powder_on_some_cooked_potatoes.jpg/1920px-Putting_garlic_powder_on_some_cooked_potatoes.jpg",
  },
  "/images/products/powders/nutmeg-powder-hero.webp": {
    author: "Dominikmatus",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Nutmeg-spice.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Nutmeg-spice.jpg/1920px-Nutmeg-spice.jpg",
  },
  "/images/products/powders/nutmeg-powder-applications.webp": {
    author: "Missvain",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Eggnog_at_Patrona_-_December_2023_-_Sarah_Stierch_02.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Eggnog_at_Patrona_-_December_2023_-_Sarah_Stierch_02.jpg/1920px-Eggnog_at_Patrona_-_December_2023_-_Sarah_Stierch_02.jpg",
  },
  "/images/products/powders/nutmeg-powder-fruit.webp": {
    author: "Schlawensko",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Nutmeg_fruit_with_mace.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Nutmeg_fruit_with_mace.jpg/1920px-Nutmeg_fruit_with_mace.jpg",
  },
  "/images/products/powders/nutmeg-powder-kernels.webp": {
    author: "Misterneedlemouse",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Whole_Nutmeg.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Whole_Nutmeg.jpg/1920px-Whole_Nutmeg.jpg",
  },
  "/images/products/powders/white-pepper-powder-hero.webp": {
    author: "Susan Slater",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:White_pepper_(ground).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/White_pepper_%28ground%29.jpg/1920px-White_pepper_%28ground%29.jpg",
  },
  "/images/products/powders/white-pepper-powder-applications.webp": {
    author: "Yausheungbon",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:HK_Sheung_Wan_Daimond_Club_Restaurant_food_%E8%83%A1%E6%A4%92%E7%B2%89_White_pepper_%E7%9A%AE%E8%9B%8B%E7%98%A6%E8%82%89%E7%B2%A5_Century_Egg_Congee_May-2012.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/HK_Sheung_Wan_Daimond_Club_Restaurant_food_%E8%83%A1%E6%A4%92%E7%B2%89_White_pepper_%E7%9A%AE%E8%9B%8B%E7%98%A6%E8%82%89%E7%B2%A5_Century_Egg_Congee_May-2012.JPG/1920px-HK_Sheung_Wan_Daimond_Club_Restaurant_food_%E8%83%A1%E6%A4%92%E7%B2%89_White_pepper_%E7%9A%AE%E8%9B%8B%E7%98%A6%E8%82%89%E7%B2%A5_Century_Egg_Congee_May-2012.JPG",
  },
  "/images/Blog/ground-black-pepper-quality-aroma-grind-and-purity.webp": {
    author: "Alexander Klepnev",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:%D0%A1%D0%B2%D0%B5%D0%B6%D0%B5%D0%BC%D0%BE%D0%BB%D0%BE%D1%82%D1%8B%D0%B9_%D1%87%D0%B5%D1%80%D0%BD%D1%8B%D0%B9_%D0%BF%D0%B5%D1%80%D0%B5%D1%86.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/%D0%A1%D0%B2%D0%B5%D0%B6%D0%B5%D0%BC%D0%BE%D0%BB%D0%BE%D1%82%D1%8B%D0%B9_%D1%87%D0%B5%D1%80%D0%BD%D1%8B%D0%B9_%D0%BF%D0%B5%D1%80%D0%B5%D1%86.jpg/1920px-%D0%A1%D0%B2%D0%B5%D0%B6%D0%B5%D0%BC%D0%BE%D0%BB%D0%BE%D1%82%D1%8B%D0%B9_%D1%87%D0%B5%D1%80%D0%BD%D1%8B%D0%B9_%D0%BF%D0%B5%D1%80%D0%B5%D1%86.jpg",
  },
  "/images/Blog/how-black-peppercorns-are-ground-without-losing-aroma.webp": {
    author: "Ben Schumin",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Shallow_focus_on_salt_and_pepper_shakers.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Shallow_focus_on_salt_and_pepper_shakers.jpg/1920px-Shallow_focus_on_salt_and_pepper_shakers.jpg",
  },
  "/images/Blog/black-pepper-powder-in-seasonings-meat-products-and-ready-meals.webp": {
    author: "Andy Li",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Black_pepper_tofu_fried_udon_-_Stir_Fry_by_CK.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Black_pepper_tofu_fried_udon_-_Stir_Fry_by_CK.jpg/1920px-Black_pepper_tofu_fried_udon_-_Stir_Fry_by_CK.jpg",
  },
  "/images/Blog/coriander-seeds-powder-export-guide-colour-aroma-and-packing.webp": {
    author: "Ajay Suresh from New York, NY, USA",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Indian_Spices_(49696133942).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Indian_Spices_%2849696133942%29.jpg/1920px-Indian_Spices_%2849696133942%29.jpg",
  },
  "/images/Blog/sourcing-coriander-powder-from-whole-seed-to-ground-spice.webp": {
    author: "Ketandelhiwala",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Spices_container.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Spices_container.jpg/1920px-Spices_container.jpg",
  },
  "/images/Blog/ground-coriander-in-curry-powders-masalas-and-bakery.webp": {
    author: "Testmaskara",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Spice_box.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Spice_box.jpg/1920px-Spice_box.jpg",
  },
  "/images/Blog/dry-mango-powder-quality-tang-colour-and-freshness.webp": {
    author: "Miansari66",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Dried_Mango_Slices.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Dried_Mango_Slices.JPG/1920px-Dried_Mango_Slices.JPG",
  },
  "/images/Blog/from-green-mango-to-amchur-how-dry-mango-powder-is-made.webp": {
    author: "Lalsing Vanya Valavi from Dhadgaon (Akrani), Nandurbar",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Close-up_of_Sun-dried_sliced_mangoes.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/5/51/Close-up_of_Sun-dried_sliced_mangoes.jpg",
  },
  "/images/Blog/dry-mango-powder-amchur-in-chaat-masala-chutneys-and-snacks.webp": {
    author: "Miansari66",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Punjabi_Chana_Chaat.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Punjabi_Chana_Chaat.JPG/1920px-Punjabi_Chana_Chaat.JPG",
  },
  "/images/Blog/sourcing-garam-masala-agreeing-a-blend-recipe-with-your-supplier.webp": {
    author: "spurekar",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Indian_spices_(garam_masala_components)_(49684334741).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Indian_spices_%28garam_masala_components%29_%2849684334741%29.jpg",
  },
  "/images/Blog/importing-garam-masala-in-bulk-specifications-packing-and-labelling.webp": {
    author: "Ajay Suresh from New York, NY, USA",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Garam_Masala_(49695826136).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Garam_Masala_%2849695826136%29.jpg/1920px-Garam_Masala_%2849695826136%29.jpg",
  },
  "/images/Blog/how-food-makers-use-garam-masala-in-curries-rice-and-marinades.webp": {
    author: "Miansari66",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Iraqi_Chicken_Biryani.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Iraqi_Chicken_Biryani.jpg/1920px-Iraqi_Chicken_Biryani.jpg",
  },
  "/images/Blog/white-pepper-powder-quality-colour-aroma-and-fineness.webp": {
    author: "Junyu-K",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:202408_%E9%99%84%E8%91%97%E8%AA%BF%E5%91%B3%E7%BD%90%E9%A0%82%E9%83%A8%E7%9A%84%E7%99%BD%E8%83%A1%E6%A4%92%E7%B2%89.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/202408_%E9%99%84%E8%91%97%E8%AA%BF%E5%91%B3%E7%BD%90%E9%A0%82%E9%83%A8%E7%9A%84%E7%99%BD%E8%83%A1%E6%A4%92%E7%B2%89.jpg/1920px-202408_%E9%99%84%E8%91%97%E8%AA%BF%E5%91%B3%E7%BD%90%E9%A0%82%E9%83%A8%E7%9A%84%E7%99%BD%E8%83%A1%E6%A4%92%E7%B2%89.jpg",
  },
  "/images/Blog/using-white-pepper-powder-in-sauces-soups-and-seasonings.webp": {
    author: "Evan-Amos",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Hot-and-Sour-Soup-Bowl.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Hot-and-Sour-Soup-Bowl.jpg/1920px-Hot-and-Sour-Soup-Bowl.jpg",
  },
  "/images/Blog/importing-white-pepper-powder-specifications-and-packing.webp": {
    author: "Miansari66",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:White_pepper_whole.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/White_pepper_whole.JPG/1920px-White_pepper_whole.JPG",
  },
  "/images/Blog/buying-nutmeg-powder-what-to-check-in-a-sample.webp": {
    author: "Frank C. Müller",
    license: "CC BY 2.0 de",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/de/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Muskatreibe_fcm.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Muskatreibe_fcm.jpg/1920px-Muskatreibe_fcm.jpg",
  },
  "/images/Blog/nutmeg-powder-in-bakery-dairy-and-beverage-production.webp": {
    author: "Shisma",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Pumpkin_pie_19_41_04_872000.jpeg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Pumpkin_pie_19_41_04_872000.jpeg/1920px-Pumpkin_pie_19_41_04_872000.jpeg",
  },
  "/images/Blog/storing-nutmeg-powder-to-protect-its-aroma.webp": {
    author: "Miansari66",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Nutmeg_whole.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Nutmeg_whole.JPG/1920px-Nutmeg_whole.JPG",
  },
  "/images/Blog/dry-ginger-powder-quality-colour-pungency-and-fibre.webp": {
    author: "Obsidi♠nSoul",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Ginger_powder.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Ginger_powder.JPG/1920px-Ginger_powder.JPG",
  },
  "/images/Blog/from-rhizome-to-sonth-how-dry-ginger-powder-is-made.webp": {
    author: "Judethedeus",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Dried_Ginger_Rhizomes.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Dried_Ginger_Rhizomes.jpg/1920px-Dried_Ginger_Rhizomes.jpg",
  },
  "/images/Blog/exporting-dry-ginger-powder-packaging-labelling-and-shipping.webp": {
    author: "Miansari66",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Ginger_dry.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Ginger_dry.JPG/1920px-Ginger_dry.JPG",
  },
  "/images/Blog/buying-clove-powder-aroma-colour-and-purity-checks.webp": {
    author: "tinofrey",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Syzygium_aromaticum_drying.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Syzygium_aromaticum_drying.jpg/1920px-Syzygium_aromaticum_drying.jpg",
  },
  "/images/Blog/why-clove-powder-loses-aroma-faster-than-whole-cloves.webp": {
    author: "Jacek Halicki",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:2023_Go%C5%BAdziki.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/2023_Go%C5%BAdziki.jpg/1920px-2023_Go%C5%BAdziki.jpg",
  },
  "/images/Blog/using-clove-powder-in-meat-sauce-and-bakery-production.webp": {
    author: "Viceskeeni2",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Lebkuchen_supermarkt_2.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Lebkuchen_supermarkt_2.jpg/1920px-Lebkuchen_supermarkt_2.jpg",
  },
  "/images/Blog/frozen-green-peas-size-grading-colour-and-iqf-quality.webp": {
    author: "Amada44",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Green_peas_8926.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Green_peas_8926.jpg/1920px-Green_peas_8926.jpg",
  },
  "/images/Blog/maintaining-the-cold-chain-for-frozen-peas.webp": {
    author: "AJC1",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Something_Beginning_With_Pea_(Explored)_-_Flickr_-_AJC1.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Something_Beginning_With_Pea_%28Explored%29_-_Flickr_-_AJC1.jpg/1920px-Something_Beginning_With_Pea_%28Explored%29_-_Flickr_-_AJC1.jpg",
  },
  "/images/Blog/frozen-peas-in-ready-meals-food-service-and-retail-packs.webp": {
    author: "U.S. Air Force photo by Senior Airman William A. O'Brien",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Washing_peas_and_carrots.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Washing_peas_and_carrots.jpg/1920px-Washing_peas_and_carrots.jpg",
  },
  "/images/Blog/selecting-tender-okra-for-export-length-and-freshness.webp": {
    author: "Attahokah",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Freshly_harvested_okra.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Freshly_harvested_okra.jpg/1920px-Freshly_harvested_okra.jpg",
  },
  "/images/Blog/handling-okra-gently-to-avoid-bruising-and-browning.webp": {
    author: "BorisAhonon",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Panier_de_gombos.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Panier_de_gombos.jpg/1920px-Panier_de_gombos.jpg",
  },
  "/images/Blog/okra-in-curries-gumbo-and-frozen-food-lines.webp": {
    author: "Wajihsyed",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:BhindiCutUp.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/BhindiCutUp.jpg/1920px-BhindiCutUp.jpg",
  },
  "/images/Blog/bitter-gourd-quality-ridges-colour-and-firmness.webp": {
    author: "စာကလေး SarKaLay",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:%E1%80%80%E1%80%BC%E1%80%80%E1%80%BA%E1%80%9F%E1%80%84%E1%80%BA%E1%80%B8%E1%80%81%E1%80%AB%E1%80%B8%E1%80%9E%E1%80%AE%E1%80%B8_Bitter_Gourd.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/%E1%80%80%E1%80%BC%E1%80%80%E1%80%BA%E1%80%9F%E1%80%84%E1%80%BA%E1%80%B8%E1%80%81%E1%80%AB%E1%80%B8%E1%80%9E%E1%80%AE%E1%80%B8_Bitter_Gourd.jpg/1920px-%E1%80%80%E1%80%BC%E1%80%80%E1%80%BA%E1%80%9F%E1%80%84%E1%80%BA%E1%80%B8%E1%80%81%E1%80%AB%E1%80%B8%E1%80%9E%E1%80%AE%E1%80%B8_Bitter_Gourd.jpg",
  },
  "/images/Blog/slowing-ripening-storing-bitter-gourd-for-shipment.webp": {
    author: "Emőke Dénes",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Cucurbitales_-_Momordica_charantia_-_4.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Cucurbitales_-_Momordica_charantia_-_4.jpg/1920px-Cucurbitales_-_Momordica_charantia_-_4.jpg",
  },
  "/images/Blog/bitter-gourd-in-asian-cooking-and-juices.webp": {
    author: "Saphabodi",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Neary_Khmer,_2018-01-02_(009).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Neary_Khmer%2C_2018-01-02_%28009%29.jpg/1920px-Neary_Khmer%2C_2018-01-02_%28009%29.jpg",
  },
  "/images/Blog/eggplant-export-guide-gloss-shape-and-firmness.webp": {
    author: "USDAgov",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:The_USDA_Farmers_Market_on_the_National_Mall_during_the_2023_market_season_is_the_Department%E2%80%99s_own_%E2%80%9Cliving_laboratory%E2%80%9D_for_farmers_market_operations_across_the_country_-_13.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/The_USDA_Farmers_Market_on_the_National_Mall_during_the_2023_market_season_is_the_Department%E2%80%99s_own_%E2%80%9Cliving_laboratory%E2%80%9D_for_farmers_market_operations_across_the_country_-_13.jpg/1920px-thumbnail.jpg",
  },
  "/images/Blog/protecting-eggplant-from-chilling-injury-in-transit.webp": {
    author: "Mx. Granger",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Fairy_Tale_Eggplant.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Fairy_Tale_Eggplant.jpg/1920px-Fairy_Tale_Eggplant.jpg",
  },
  "/images/Blog/round-long-and-baby-eggplant-matching-variety-to-market.webp": {
    author: "Fructibus",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Five_eggplants_2017.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Five_eggplants_2017.jpg/1920px-Five_eggplants_2017.jpg",
  },
  "/images/Blog/fresh-drumsticks-pod-length-tenderness-and-colour.webp": {
    author: "Judgefloro",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:2301Moringa_oleifera_pod_(seedpod)_textures_20.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/2301Moringa_oleifera_pod_%28seedpod%29_textures_20.jpg/1920px-2301Moringa_oleifera_pod_%28seedpod%29_textures_20.jpg",
  },
  "/images/Blog/keeping-drumsticks-fresh-from-farm-to-market.webp": {
    author: "David E Mead",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Ben-oil_tree_pods_(marketed)_1.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Ben-oil_tree_pods_%28marketed%29_1.jpg/1920px-Ben-oil_tree_pods_%28marketed%29_1.jpg",
  },
  "/images/Blog/drumsticks-in-sambar-curries-and-frozen-packs.webp": {
    author: "Vashisthapathak2015",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Drumstick_(sahjan)_ki_sabzi.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Drumstick_%28sahjan%29_ki_sabzi.JPG/1920px-Drumstick_%28sahjan%29_ki_sabzi.JPG",
  },
  "/images/Blog/fresh-green-beans-snap-straightness-and-size-grading.webp": {
    author: "Undeka 11",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Macro_of_Fresh_Green_Beans_Buncis.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Macro_of_Fresh_Green_Beans_Buncis.jpg/1920px-Macro_of_Fresh_Green_Beans_Buncis.jpg",
  },
  "/images/Blog/pre-cooling-green-beans-for-longer-freshness.webp": {
    author: "USAID Africa Bureau",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Harvesting_beans_(5762966966).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/b/b7/Harvesting_beans_%285762966966%29.jpg",
  },
  "/images/Blog/green-beans-for-retail-food-service-and-freezing.webp": {
    author: "Warden",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    source: "https://commons.wikimedia.org/wiki/File:Blanching.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Blanching.jpg/1920px-Blanching.jpg",
  },
  "/images/Blog/building-a-mixed-agricultural-order-from-india.webp": {
    author: "Ganesh Mohan T",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Vegetables_from_Shillong_01.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Vegetables_from_Shillong_01.jpg/1920px-Vegetables_from_Shillong_01.jpg",
  },
  "/images/Blog/seasonality-planning-fresh-produce-imports-around-harvests.webp": {
    author: "USDAgov",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Harvest_(20110505-RD-LSC-0157).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Harvest_%2820110505-RD-LSC-0157%29.jpg/1920px-Harvest_%2820110505-RD-LSC-0157%29.jpg",
  },
  "/images/Blog/phytosanitary-certificates-and-export-documents-for-fresh-produce.webp": {
    author: "USDAgov",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Squash_Harvest_at_Kirby_Farms_(20130920-OC-LSC-2567).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Squash_Harvest_at_Kirby_Farms_%2820130920-OC-LSC-2567%29.jpg/1920px-Squash_Harvest_at_Kirby_Farms_%2820130920-OC-LSC-2567%29.jpg",
  },
  "/images/Blog/mango-export-quality-treatment-grading-and-inspection.webp": {
    author: "Bim24",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Carabao_Mangoes_from_Cebu,_Philippines.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Carabao_Mangoes_from_Cebu%2C_Philippines.jpg/1920px-Carabao_Mangoes_from_Cebu%2C_Philippines.jpg",
  },
  "/images/Blog/ripening-and-storing-mangoes-after-arrival.webp": {
    author: "Camilopiz",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Umwembe.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Umwembe.jpg/1920px-Umwembe.jpg",
  },
  "/images/Blog/banana-export-guide-finger-length-grade-and-maturity.webp": {
    author: "Obsidian Soul",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Lakatan_banana_bunch_(Philippines)_02.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Lakatan_banana_bunch_%28Philippines%29_02.jpg/1920px-Lakatan_banana_bunch_%28Philippines%29_02.jpg",
  },
  "/images/Blog/green-shipping-and-controlled-ripening-for-bananas.webp": {
    author: "Scott Webb scottwebb",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Ripening_bananas_(Unsplash).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Ripening_bananas_%28Unsplash%29.jpg/1920px-Ripening_bananas_%28Unsplash%29.jpg",
  },
  "/images/Blog/cavendish-robusta-and-red-bananas-choosing-for-your-market.webp": {
    author: "Judgefloro",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:04242jfBaclaran_Elpidio_Quirino_Avenue_Para%C3%B1aque_Cityfvf_09.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/04242jfBaclaran_Elpidio_Quirino_Avenue_Para%C3%B1aque_Cityfvf_09.jpg/1920px-04242jfBaclaran_Elpidio_Quirino_Avenue_Para%C3%B1aque_Cityfvf_09.jpg",
  },
  "/images/Blog/table-grapes-from-india-berry-size-sugar-and-colour.webp": {
    author: "Martin Kozák",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Green_Grape_3.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Green_Grape_3.jpg/1920px-Green_Grape_3.jpg",
  },
  "/images/Blog/cold-storage-and-packing-that-keep-grapes-fresh.webp": {
    author: "W.carter",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Grape_harvest_in_Chateaux_Luna_vineyard_3.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Grape_harvest_in_Chateaux_Luna_vineyard_3.jpg/1920px-Grape_harvest_in_Chateaux_Luna_vineyard_3.jpg",
  },
  "/images/Blog/seedless-green-black-and-red-grapes-what-buyers-prefer.webp": {
    author: "Lisafern",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Red_and_green_grapes.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Red_and_green_grapes.jpg/1920px-Red_and_green_grapes.jpg",
  },
  "/images/Blog/pomegranate-export-quality-aril-colour-size-and-skin.webp": {
    author: "Ella Olsson from Stockholm, Sweden",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Pomegranates_at_farmers_market_(43134440935).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Pomegranates_at_farmers_market_%2843134440935%29.jpg/1920px-Pomegranates_at_farmers_market_%2843134440935%29.jpg",
  },
  "/images/Blog/why-pomegranates-travel-well-and-how-to-keep-them-fresh.webp": {
    author: "René Hourdry",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Pomegranates_2024D.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Pomegranates_2024D.jpg/1920px-Pomegranates_2024D.jpg",
  },
  "/images/Blog/pomegranates-for-fresh-retail-arils-and-juice.webp": {
    author: "Augustus Binu : flickr",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Pomegranate_Juice_(2019).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Pomegranate_Juice_%282019%29.jpg/1920px-Pomegranate_Juice_%282019%29.jpg",
  },
  "/images/Blog/sourcing-oranges-juice-content-peel-and-size.webp": {
    author: "safaritravelplus",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Oranges_a_fruit.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Oranges_a_fruit.jpg/1920px-Oranges_a_fruit.jpg",
  },
  "/images/Blog/storing-oranges-to-preserve-juiciness-and-peel-quality.webp": {
    author: "Erol Ahmed erol",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Fresh_Oranges_(Unsplash).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Fresh_Oranges_%28Unsplash%29.jpg/1920px-Fresh_Oranges_%28Unsplash%29.jpg",
  },
  "/images/Blog/oranges-for-the-fruit-bowl-juice-bars-and-processing.webp": {
    author: "Geoff Peters from Vancouver, BC, Canada",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Orange_juice_(3249410157).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Orange_juice_%283249410157%29.jpg/1920px-Orange_juice_%283249410157%29.jpg",
  },
  "/images/Blog/chikoo-sapota-export-guide-maturity-and-sweetness.webp": {
    author: "Daderot",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Manilkara_zapota_-_Fruit_and_Spice_Park_-_Homestead,_Florida_-_DSC09131.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Manilkara_zapota_-_Fruit_and_Spice_Park_-_Homestead%2C_Florida_-_DSC09131.jpg/1920px-Manilkara_zapota_-_Fruit_and_Spice_Park_-_Homestead%2C_Florida_-_DSC09131.jpg",
  },
  "/images/Blog/handling-chikoo-a-delicate-fruit-that-ripens-fast.webp": {
    author: "Sm faysal",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Closeup_of_Sapodilla_fruit_from_Bangladesh.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Closeup_of_Sapodilla_fruit_from_Bangladesh.jpg/1920px-Closeup_of_Sapodilla_fruit_from_Bangladesh.jpg",
  },
  "/images/Blog/chikoo-in-milkshakes-desserts-and-ice-cream.webp": {
    author: "Daniel Di Palma",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Manilkara_zapota_-_Nispero_fruit_cut_in_two.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Manilkara_zapota_-_Nispero_fruit_cut_in_two.jpg/1920px-Manilkara_zapota_-_Nispero_fruit_cut_in_two.jpg",
  },
  "/images/Blog/papaya-export-guide-colour-break-weight-and-firmness.webp": {
    author: "Hardyplants",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Fruit_of_papaya.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Fruit_of_papaya.jpg/1920px-Fruit_of_papaya.jpg",
  },
  "/images/Blog/shipping-papaya-temperature-ripening-and-handling.webp": {
    author: "Kozak005",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Papaya_in_Mandaue_Public_Market.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Papaya_in_Mandaue_Public_Market.jpg/1920px-Papaya_in_Mandaue_Public_Market.jpg",
  },
  "/images/Blog/papaya-for-fresh-retail-fruit-salads-and-pulp.webp": {
    author: "Leon Brooks",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Pawpaw_fruit_sliced.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Pawpaw_fruit_sliced.jpg/1920px-Pawpaw_fruit_sliced.jpg",
  },
  "/images/Blog/guava-sourcing-white-vs-pink-flesh-size-and-aroma.webp": {
    author: "Sarang",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Guava_-_Psidium_guajava_fruit_of_Cuba.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Guava_-_Psidium_guajava_fruit_of_Cuba.jpg/1920px-Guava_-_Psidium_guajava_fruit_of_Cuba.jpg",
  },
  "/images/Blog/extending-guava-shelf-life-with-careful-post-harvest-care.webp": {
    author: "McKay Savage from London, UK",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:India_-_Koyambedu_Market_-_Guava_01_(3986991982).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/India_-_Koyambedu_Market_-_Guava_01_%283986991982%29.jpg/1920px-India_-_Koyambedu_Market_-_Guava_01_%283986991982%29.jpg",
  },
  "/images/Blog/guava-in-juices-jams-and-fresh-retail.webp": {
    author: "Zeel Patel",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Fresh_Gvava_Juice.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Fresh_Gvava_Juice.JPG/1920px-Fresh_Gvava_Juice.JPG",
  },
  "/images/Blog/boiling-drying-and-polishing-how-turmeric-is-cured.webp": {
    author: "Salammon",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Turmeric_Harvesting.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Turmeric_Harvesting.jpg/1920px-Turmeric_Harvesting.jpg",
  },
  "/images/Blog/dried-red-chilli-export-guide-heat-colour-and-stem.webp": {
    author: "Miansari66",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Red_chilli_whole_dandi_cut.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Red_chilli_whole_dandi_cut.JPG/1920px-Red_chilli_whole_dandi_cut.JPG",
  },
  "/images/Blog/teja-byadgi-and-guntur-understanding-indian-chilli-varieties.webp": {
    author: "Adityamadhav83",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Dried_Chillies_at_Grandhasiri_Village_in_Guntur_district.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Dried_Chillies_at_Grandhasiri_Village_in_Guntur_district.JPG/1920px-Dried_Chillies_at_Grandhasiri_Village_in_Guntur_district.JPG",
  },
  "/images/Blog/storing-dried-chillies-to-protect-colour-and-prevent-mould.webp": {
    author: "Rudolph.A.furtado",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Spice_Warehouse_on_Bazaar_Street_in_Mattancherry..JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Spice_Warehouse_on_Bazaar_Street_in_Mattancherry..JPG/1920px-Spice_Warehouse_on_Bazaar_Street_in_Mattancherry..JPG",
  },
  "/images/Blog/black-pepper-quality-bulk-density-size-and-aroma.webp": {
    author: "Ram!n at Persian Wikipedia",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Black_pepper_(By_R.Boroujerdi).JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Black_pepper_%28By_R.Boroujerdi%29.JPG/1920px-Black_pepper_%28By_R.Boroujerdi%29.JPG",
  },
  "/images/Blog/malabar-and-tellicherry-indian-black-pepper-grades-explained.webp": {
    author: "Miansari66",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Black_pepper_whole.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Black_pepper_whole.JPG/1920px-Black_pepper_whole.JPG",
  },
  "/images/Blog/cumin-seeds-export-guide-purity-colour-and-aroma.webp": {
    author: "Miansari66",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Cumin_seed_whole.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Cumin_seed_whole.JPG/1920px-Cumin_seed_whole.JPG",
  },
  "/images/Blog/machine-cleaning-and-sortex-how-cumin-is-prepared-for-export.webp": {
    author: "Tanvir Anjum Adib",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Cuminum_cyminum_JEERA.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Cuminum_cyminum_JEERA.jpg/1920px-Cuminum_cyminum_JEERA.jpg",
  },
  "/images/Blog/cumin-in-spice-blends-ground-cumin-and-food-processing.webp": {
    author: "Holger Casselmann",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Garam_Masala_new_2008.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Garam_Masala_new_2008.JPG/1920px-Garam_Masala_new_2008.JPG",
  },
  "/images/Blog/coriander-seeds-colour-split-content-and-aroma.webp": {
    author: "Sanjay Acharya",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Coriander_Seeds.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Coriander_Seeds.jpg/1920px-Coriander_Seeds.jpg",
  },
  "/images/Blog/eagle-scooter-and-badami-coriander-grades-explained.webp": {
    author: "Sanjay_ach",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Coriander_seeds_close_up.jpeg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Coriander_seeds_close_up.jpeg/1920px-Coriander_seeds_close_up.jpeg",
  },
  "/images/Blog/coriander-seeds-in-spice-mixes-pickling-and-brewing.webp": {
    author: "Abissada",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Whole_coriander_seeds_to_make_Du%27ah_(dukkah).JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/c/c5/Whole_coriander_seeds_to_make_Du%27ah_%28dukkah%29.JPG",
  },
  "/images/Blog/green-cardamom-grading-pod-size-colour-and-aroma.webp": {
    author: "Libreravi",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Green_Elaichi_from_India.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Green_Elaichi_from_India.jpg/1920px-Green_Elaichi_from_India.jpg",
  },
  "/images/Blog/protecting-cardamom-s-green-colour-and-fragrance.webp": {
    author: "Veganbaking.net from USA",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Cardamom_Pods_(4157454523).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Cardamom_Pods_%284157454523%29.jpg/1920px-Cardamom_Pods_%284157454523%29.jpg",
  },
  "/images/Blog/cardamom-in-tea-coffee-sweets-and-bakery.webp": {
    author: "W.carter",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Cardamom_buns.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Cardamom_buns.jpg/1920px-Cardamom_buns.jpg",
  },
  "/images/Blog/clove-quality-head-intact-colour-and-oil-content.webp": {
    author: "Jorge Barrios",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Cloves.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Cloves.JPG/1920px-Cloves.JPG",
  },
  "/images/Blog/storing-cloves-to-keep-their-aromatic-oils.webp": {
    author: "FunkyMonkey MP",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Cloves_on_wood_surface.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Cloves_on_wood_surface.jpg/1920px-Cloves_on_wood_surface.jpg",
  },
  "/images/Blog/cloves-in-spice-blends-baking-and-oil-extraction.webp": {
    author: "Friedrich Haag",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Gewuerze_004_2024_08_10.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Gewuerze_004_2024_08_10.jpg/1920px-Gewuerze_004_2024_08_10.jpg",
  },
  "/images/Blog/buying-cinnamon-quills-thickness-and-aroma.webp": {
    author: "Simon A. Eugster",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Cinnamomum_verum_spices.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Cinnamomum_verum_spices.jpg/1920px-Cinnamomum_verum_spices.jpg",
  },
  "/images/Blog/cinnamon-vs-cassia-knowing-what-you-are-sourcing.webp": {
    author: "Fumikas Sagisavas",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Cassia_bark_(2).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Cassia_bark_%282%29.jpg/1920px-Cassia_bark_%282%29.jpg",
  },
  "/images/Blog/mustard-seeds-export-guide-black-brown-and-yellow.webp": {
    author: "Veganbaking.net from USA",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Mustard_Seeds_(8630655446).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Mustard_Seeds_%288630655446%29.jpg/1920px-Mustard_Seeds_%288630655446%29.jpg",
  },
  "/images/Blog/cleaning-and-grading-mustard-seeds-for-export.webp": {
    author: "Theredgiant",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Black_mustard_seeds.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Black_mustard_seeds.jpg/1920px-Black_mustard_seeds.jpg",
  },
  "/images/Blog/mustard-seeds-for-tempering-pickles-and-condiments.webp": {
    author: "Dharmadhyaksha",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Spices_in_an_Indian_kitchen.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Spices_in_an_Indian_kitchen.JPG/1920px-Spices_in_an_Indian_kitchen.JPG",
  },
  "/images/Blog/fennel-seeds-quality-green-colour-size-and-sweetness.webp": {
    author: "NanaYawBotar",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Fennel_seeds_01.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/b/bb/Fennel_seeds_01.jpg",
  },
  "/images/Blog/keeping-fennel-seeds-green-and-fragrant-in-storage.webp": {
    author: "CNEcija12345",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Fennel_as_food.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Fennel_as_food.jpg/1920px-Fennel_as_food.jpg",
  },
  "/images/Blog/fennel-seeds-as-mouth-freshener-in-teas-and-baking.webp": {
    author: "Martyvis",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Green_Mukhwas.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Green_Mukhwas.jpg/1920px-Green_Mukhwas.jpg",
  },
  "/images/Blog/fenugreek-seeds-quality-colour-cleanliness-and-seed-condition.webp": {
    author: "Bhaskaranaidu",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Mentulu_2.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Mentulu_2.JPG/1920px-Mentulu_2.JPG",
  },
  "/images/Blog/fenugreek-seeds-in-curry-powders-pickles-and-seasonings.webp": {
    author: "Miansari66",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Curry_Powder.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Curry_Powder.JPG/1920px-Curry_Powder.JPG",
  },
  "/images/Blog/storing-fenugreek-seeds-moisture-pests-and-aroma.webp": {
    author: "കാക്കര",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Fenugreek_-_%E0%B4%89%E0%B4%B2%E0%B5%81%E0%B4%B5.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Fenugreek_-_%E0%B4%89%E0%B4%B2%E0%B5%81%E0%B4%B5.JPG/1920px-Fenugreek_-_%E0%B4%89%E0%B4%B2%E0%B5%81%E0%B4%B5.JPG",
  },
  "/images/Blog/buying-psyllium-seed-for-husk-processing-what-to-check.webp": {
    author: "Krzysztof Ziarnek, Kenraiz",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Plantago_ovata_kz13.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Plantago_ovata_kz13.jpg/1920px-Plantago_ovata_kz13.jpg",
  },
  "/images/Blog/from-psyllium-seed-to-husk-how-whole-seed-is-processed.webp": {
    author: "Bastique (Cary Bass)",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Psyllium_seed_husks.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Psyllium_seed_husks.JPG/1920px-Psyllium_seed_husks.JPG",
  },
  "/images/Blog/exporting-psyllium-seed-documentation-packing-and-labelling.webp": {
    author: "Oliwier Brzezinski",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Psyllium_Husk.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Psyllium_Husk.jpg/1920px-Psyllium_Husk.jpg",
  },
  "/images/Blog/fresh-and-dried-ginger-what-importers-should-check.webp": {
    author: "Miansari66",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Fresh_Ginger.JPG",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Fresh_Ginger.JPG/1920px-Fresh_Ginger.JPG",
  },
  "/images/Blog/storing-ginger-to-prevent-sprouting-and-shrivelling.webp": {
    author: "Fumikas Sagisavas",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Fresh_ginger_(20240131).jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Fresh_ginger_%2820240131%29.jpg/1920px-Fresh_ginger_%2820240131%29.jpg",
  },
  "/images/Blog/ginger-in-teas-sauces-bakery-and-beverages.webp": {
    author: "Trupti.gauns",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Ginger_Tea_.jpg",
    original: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Ginger_Tea_.jpg/1920px-Ginger_Tea_.jpg",
  },
};
